### ISSUE TITLE
Obsolete term ids used as alt_ids on DOID:1234

### ISSUE THREAD

**Issue by kimrutherford** [DiseaseOntology/HumanDiseaseOntology#106]
While loading HumanDO.obo into an instance of Canto (https://github.com/pombase/canto) we noticed that the alt_ids of DOID:1234 (DOID:10827 and DOID:13350) are also the ids of two obsolete terms.  This failed to load into Canto because it assumes the an ID refers to at most one term.  We can work around this for loading but @cmungall suggested we report it to you.

**Comment by lschriml** [comment]
Hello Kim,
 thank you for letting us know you were having a problem with loading DO.
Alt IDs get populated when we merge records, in this case after the merge,
the two alt ids were later obsoleted. 

For your data loading, could you exclude obsoleted terms, to avoid the problem ? 

Cheers,
Lynn

**Comment by kimrutherford** [comment]
Hi Lynn.  Thanks for your reply.

> For your data loading, could you exclude obsoleted terms, to avoid the problem ? 

We generally need to keep obsolete terms because they may still be used in annotations in Canto (and Chado).  If we exclude the obsolete terms when we reload an ontology we'd have to drop any existing annotations that refer to those terms.  We fix those annotations as we find them but it may take time for a curator to change the annotation to use the correct term.

Kim.

**Comment by airvine** [comment]
Hi Lynn,

This issue was originally raised a few months ago. Here I copy a comment I made with regard to the issue, originally posted here: [https://github.com/pombase/canto/issues/1029#issuecomment-158036291](url)

I think is issue is more generally to do with IDs that are simultaneously alt_ids, and actually has nothing to do with obsoletion.

In the original example the disease ontology had two terms with alt_ids, both of which also were also used as term IDs in terms which happen to have been made obsolete. But when I looked at an earlier version of the disease ontology I also find a third term with an alt_id which is the term ID of another term, but in this case the term is not obsolete. In the later version of the ontology, this alt_id has been removed.

**Comment by cmungall** [comment]
This needs to be fixed in the DO. I can provide check scripts in the Makefile if that helps

**Comment by lschriml** [comment]
These alt ids have been removed. 
Thank you for helping us get this fixed.
The fixes are in our do-edit.owl file in our github repository.
These will be pushed to our diod.obo and owl files tomorrow.
Thank you Chris, a check script would be great !! 
Cheers,
Lynn
