### ISSUE TITLE
New Term Request: breast implant illness

### ISSUE THREAD

**Issue by rankishore** [DiseaseOntology/HumanDiseaseOntology#1122]
Hello DO folks,
I am curating a publication from microPublication Biology, see https://www.micropublication.org/journals/biology/micropub-biology-000732, which has used C. elegans to study Breast Implant Illness (BII). While DO has the term "breast implant-associated anaplastic large cell lymphoma (DOID:0070333)" which is quite specific, it does not have the term "breast implant illness" which would be suitable to curate this pub and perhaps others.

So I suggest a new term:
"breast implant illness (BII)" with a synonym: silicone toxicity.

References:
1. https://www.micropublication.org/journals/biology/micropub-biology-000732
2. Brawer 2019. The Clever Deception by Silicone Gel-filled Breast Implant Manufacturers Regarding the Phenomenon of Gel Bleed. Journal of Rhumatic Diseases and Treatment 5: 077.
[10.23937/2469-5726/1510077](https://doi.org/10.23937/2469-5726/1510077)
3. Wee CE, Younis J, Isbester K, Smith A, Wangler B, Sarode AL, et al., Feng LJ. 2020. Understanding Breast Implant Illness, Before and After Explantation: A Patient-Reported Outcomes Study. Ann Plast Surg 85: S82-S86.
[PubMed](https://www.ncbi.nlm.nih.gov/pubmed/32530850)

Thanks
Ranjana Kishore (ranjana@caltech.edu)
WormBase| Alliance of Genome Resources

**Comment by lschriml** [comment]
Thank you for the new term Ranjana !!

**Comment by lschriml** [comment]
Adding this new term as a syndrome. 


Looking at the literature for this term:

**https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9060741/**

A significant population of women currently pursue bilateral breast implant removal in hopes to alleviate a constellation of symptoms anecdotally known as **“breast implant illness”.** 
This is not yet an accepted clinical entity due to the lack of sound literature on the subject.

**https://my.clevelandclinic.org/health/diseases/23366-breast-implant-illness**

Breast implant illness (BII) is a collection of symptoms that occur in people with breast implants. There isn't an official medical diagnosis for BII. Symptoms may include fatigue, joint pain, brain fog, dry eyes and many other health concerns. 

**Other names for breast implant illness include:**

Breast implant disease.
Autoimmune/inflammatory syndrome induced by adjuvants (ASIA).
Silicone implant illness.

**https://pubmed.ncbi.nlm.nih.gov/34882509/**

More than one million breast augmentation procedures using **silicone breast implants (SBI)** have been performed worldwide. Adverse events of SBI include local complications such as pain, swelling, redness, infections, capsular contracture, implant rupture, and gel-bleed. Furthermore, patients experience systemic symptoms such as chronic fatigue, arthralgias, myalgias, pyrexia, sicca, and cognitive dysfunction. These symptoms received different names such as **autoimmune/autoinflammatory syndrome induced by adjuvants (ASIA**) due to silicone incompatibility syndrome and breast implant illness **(BII)**. Because of chronic immune activation, BII/ASIA, allergies, autoimmune diseases, immune deficiencies, and finally lymphomas may develop in SBI patients.

Expert opinion: We conclude that there is a causal association between SBIs and BII/ASIA. Using data derived from patients with BII/ASIA and from other medically implanted devices, there appears to be clear pathogenic relationship between SBI and BII/ASIA. 

**https://casereports.bmj.com/content/2017/bcr-2016-218709**

**Autoimmune/inflammatory syndrome induced by adjuvants due to silicone exposure from ruptured silicone implants** can lead to different interstitial lung manifestations predominantly with granuloma evolvement, leading to the so-called **silicone implant incompatibility syndrome** (SIIS).

**https://pubmed.ncbi.nlm.nih.gov/36276594/**

Two Cases of Autoimmune Syndrome Induced by Adjuvants (ASIA): A Multifaceted Condition Calling for a Multidisciplinary Approach

**autoimmune syndrome induced by adjuvants (ASIA)**

**Comment by lschriml** [comment]
New term added to the DO.
