### ISSUE TITLE
relation between hypoglycemia and specific types of hypoglycemia

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1127]
@lschriml 
Also from David

"I notice that there are several specific types of hypoglycemia in the ontology, but the most generic term (DOID:9993) is a leaf node. I think the more specific types are missing parentage to the generic type (eg. DOID:13317 and kids)."

DOID:13317 is hyperinsulinemic hypoglycemia which is a child of carbohydrate metabolic disorder

hypoglycemia is a child of glucose metabolism disease which in turn is a child of carbohydrate metabolic disorder. Is there a reason that hyperinsulinemic hypoglycemia is not a child of hypoglycemia? Looking at the definitions for each: 

hypoglycemia - A glucose metabolism disease that is characterized by abnormally low levels of blood glucose

 hyperinsulinemic hypoglycemia - A carbohydrate metabolic disorder that involves low blood glucose resulting from an excess of insulin.

it seems like hyperinsulinemic hypoglycemia could be made a child of hypoglycemia but maybe I am missing something?

Also while looking into this I noticed that hypoglycemia has the subclass axiom "'has phenotype' some 'Abnormal blood glucose concentration'" Is there a reason that Abnormal blood glucose concentration was used instead of 'Hypoglycemia' (HP:0001943)?  I'm guessing it was to avoid loading an HPO term that matches a DO term, but using abnormal loses a lot of the specificity. I was initially thinking that if we don't make hyperinsulinemic hypoglycemia a child of hypoglycemia that the phenotype subaxioms could be used to infer this but I don't know if that would work when using abnormal blood glucose concentration.

Anna and I have recently been discussing the hypoglycemia/decreased circulating glucose level issue with Leigh from HPO. I think she is planning to talk to Peter about this. The MP has 2 terms decreased circulating glucose level (MP:0005560) and hypoglycemia (MP:0000189), where hypoglycemia is defined as generally referring to the pathological condition and the 'pathological' modifier is included in the logical definition. The HPO has only a single term where the text definition matches decreased circulating glucose level but the logical definition matches the one in MP for hypoglycemia. 

I'll give you a heads up if I hear back from Leigh on this.

Sue

**Comment by lschriml** [comment]
Is there a reason that hyperinsulinemic hypoglycemia is not a child of hypoglycemia
 --> no it should be a child. 
I see that the SubClassOf axiom is defined for hypoglycemia, it should be an EQ. 

 Is there a reason that Abnormal blood glucose concentration was used instead of 'Hypoglycemia' (HP:0001943)? I'm guessing it was to avoid loading an HPO term that matches a DO term, but using abnormal loses a lot of the specificity
    --> yes, that is the reason, also we received feedback from several users that having HPO terms that are also DO terms caused issues. 
     --> The way DO has been handling this, is to define the relationship by replacing the 'has phenotype' with a 'disease has feature' RO term. This relates where one disease is a feature of another disease.
   In this case, I will leave the less specific HPO axiom and add in the more specific 'disease has feature' axiom

<img width="483" alt="Screen Shot 2023-03-01 at 11 16 40 AM" src="https://user-images.githubusercontent.com/4333069/222198571-787c59d5-9f3e-44f1-8244-890910e2f3a3.png">

The DO has been updated.
Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn!
