### ISSUE TITLE
Addition of diseases to the cancer slim obo file

### ISSUE THREAD

**Issue by acoffman** [DiseaseOntology/HumanDiseaseOntology#116]
Hi!

I am working on an application that is utilizing the [cancer slim obo file](https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/subsets/DO_cancer_slim.obo). I am curious about the criteria that are used to select diseases for inclusion in that subset. My coworkers @kkrysiak and @malachig have identified some diseases which they would have expected to be in the cancer set, but were not. Namely:

````
hemorrhagic thrombocythemia [DOID: 2224]
chronic myeloproliferative disease [DOID: 2226]
merkel cell carcinoma [DOID:3965]
````

Is this an oversight, or were these diseases intentionally omitted from the set?

Thanks for your time and effort maintaining this great resource! 
-Adam

**Comment by elviram** [comment]
Hello acoffman,
the initial set of diseases included in the slim were based on the different resources involved in the effort. We are more than happy to add more for the adopters of the DO_cancer_slim. 
Are those three the only ones you would need?
Also, could you give us some information on what you are working on?

Thank you,
Elvira

**Comment by malachig** [comment]
Dear Elvira, 

We have chosen the DO as the disease ontology of the CIViC project (Clinical Interpretation of Variants in Cancer). www.civicdb.org.  We are requiring curators from the community to identify a valid disease according to the DO for every evidence record created in CIViC.  

To make it easier to enter diseases during manual curation of the literature, we use a typeahead feature to display possible valid disease names.  Since the scope of the resource is limited to cancer, we used the cancer slim obo file.  All diseases would be too cluttered with disease outside our score.  For the most part this satisfies our needs, but we are encountering some clearly cancer related diseases that are missing.  Here are three more:

```
Her2-receptor positive breast cancer - DOID:0060079
Her2-receptor negative breast cancer - DOID:0060080
triple-receptor negative breast cancer - DOID:0060081 
```

Maybe a less "slim" version that had all entries related to cancer could be created?  Or we can continue to let you know about cases like this as they arrive.  Though, I do worry that curators will just choose a less suitable option not realizing that are more specific cancer subtype was actually available in the DO.

**Comment by goodb** [comment]
I'm wondering if a Web service such as BioPortal, the EBI's OLS, or WikiData could be used to extract the term subset you need dynamically with a query rather than relying on a slim? As one example, you could use the Wikidata query engine to retrieve all the subclasses of cancer that have a DOID.  [Like this](https://query.wikidata.org/#PREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0APREFIX%20p%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2F%3E%0A%0ASELECT%20distinct%20%3FdiseaseLabel%20%3Fdisease%20%3FdoID%20%0AWHERE%20%0A%7B%0A%20%20%3Fdisease%20wdt%3AP279*%20wd%3AQ12078%20.%20%20%23%20find%20subclasses%20of%20cancer%0A%20%20%3Fdisease%20wdt%3AP699%20%3FdoID%20.%20%23%20with%20a%20doid%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%0A%20%20%7D%0A%7D)

If you used wikidata, your curation team could adapt it on the fly, without requesting and waiting for approval.  Of course so could other people.. so you would want to have friends that could help you figure out a pattern for ensuring things didn't get screwed up and ensuring that the DO people were aware of the changes you made so that they could consider incorporating them into their ontology.  but I digress.

**Comment by obigriffith** [comment]
Several others that I came across that are missing in cancer_slim but are definitely under cancer:
endometrial stromal sarcoma
vaginal endometrial stromal sarcoma
cervical endometrial stromal sarcoma
uterine corpus endometrial stromal sarcoma

What we are seeing is that CIViC curators do end up just choosing the best/closest match. For example, in this case CIViC submissions were put under 'endometrial cancer'. That is correct but less specific than we would like. 

It would be awesome if DO supported a DO_cancer.obo that was complete (not slim).

**Comment by lschriml** [comment]
We have added these terms to our DO cancer slim, these changes will be incorporated into our OBO file with Friday's public release. 
Cheers,
Lynn
