### ISSUE TITLE
multiple symmetric lipomatosis AND lipoma

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1228]
multiple symmetric lipomatosis (DOID:14116) and lipoma (DOID:3315) share the OMIM xref OMIM:151900 

OMIM:151900  was Lipomatosis, Multiple but is now Lipomatosis, Familial Multiple; FML 

It is unclear if OMIM:151900 should be an xref to either of these DO terms.

DOID:14116 has a second OMIM xref 151800 (Lipomatosis, multiple symmetric, with or without peripheral neuropathy) which seems like the correct xref based on the synonyms for this entry. Note the DO term currently lacks a definition.

DOID:3315 is just general lipoma which also doesn't fit the OMIM definition for 151900 "rare autosomal dominant disorder characterized by numerous encapsulated lipomas on the trunk and extremities"

I would suggest removing 151900 from both of the current DO terms and adding a new term to represent the disease for 151900.

Thanks,
Sue

**Comment by allenbaron** [comment]
lipoma (DOID:3315) and lipomatosis (DOID:3153), along with all of its children, currently lack definitions. It's clear we need to revise this classification more completely. I'll work to get this done by the October release.

**Comment by allenbaron** [comment]
It seems to me that 'familial multiple lipomatosis'  (OMIM:151900) could be the same as lipomatosis (DOID:3153), but I will add it as a new disease as you suggested because lipomatosis in the DO is a grouping disease with children that vary in genetic cause, while the OMIM entry points heavily to genetic linkage on chromosome 12.

Just noting that NCI has the same arrangement as the DO with lipomatosis (NCI:C3193) as a grouping term and lacks a term for 'familial multiple lipomatosis'. Orphanet, on the other hand, has no grouping term and has 'familial multiple lipomatosis' as a sibling to other lipomatosis diseases (that the DO currently has as children of lipomatosis). Not surprisingly, there's a lack of consistency.

Splitting now and merging later, if lipomatosis and 'Familial Multiple Lipomatosis' turn out to be the same thing, seems like the safest approach from a curation perspective.

**Comment by allenbaron** [comment]
It seems to me that 'familial multiple lipomatosis'  (OMIM:151900) could be the same as lipomatosis (DOID:3153), but I will add it as a new disease as you suggested because lipomatosis in the DO is a grouping disease with children that vary in genetic cause, while the OMIM entry points heavily to genetic linkage on chromosome 12.

Just noting that NCI has the same arrangement as the DO with lipomatosis (NCI:C3193) as a grouping term and lacks a term for 'familial multiple lipomatosis'. Orphanet, on the other hand, has no grouping term and has 'familial multiple lipomatosis' as a sibling to other lipomatosis diseases (that the DO currently has as children of lipomatosis). Not surprisingly, there's a lack of consistency.

If lipomatosis and 'familial multiple lipomatosis' turn out to be the same thing, splitting now and merging later seems like the safest approach from a curation perspective.

Just noting that NCI has the same arrangement as the DO with lipomatosis (NCI:C3193) as a grouping term and lacks a term for 'familial multiple lipomatosis'. Orphanet, on the other hand, has no grouping term and has 'familial multiple lipomatosis' as a sibling to other lipomatosis diseases (that the DO currently has as children of lipomatosis). Not surprisingly, there's a lack of consistency.

If lipomatosis and 'Familial Multiple Lipomatosis' turn out to be the same thing, splitting now and merging later seems like the safest approach from a curation perspective.
