### ISSUE TITLE
Nomenclature update NAFLD to MASLD, NASH to MASH liver diseases

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#1245]
Request shared via MGI, from EFO user: 

Looking at support/documentation for this nomenclature update, details below, 
I think there is enough support to update the two names, keeping the older names as exact synonyms. 

-- noting in PubMed that "'non-alcoholic fatty liver disease' (NAFLD)" is still being commonly used.

A 2023 paper:
     https://pubmed.ncbi.nlm.nih.gov/36976456/
https://link.springer.com/article/10.1007/s13105-023-00954-4
        states:  the nomenclature of non-alcoholic fatty liver disease (NAFLD) has been updated to MAFLD. 

https://pubmed.ncbi.nlm.nih.gov/36926229/
             -Metabolic-associated fatty liver disease: New nomenclature and approach with hot debate
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10011913/
    An international panel recently proposed an update to the terminology and diagnostic criteria for fatty liver disease. The experts proposed a change in the nomenclature from non-alcoholic fatty liver disease (NAFLD) to metabolic (dysfunction)-associated fatty liver disease (MAFLD).

https://www.aasld.org/new-nafld-nomenclature

**Comment by allenbaron** [comment]
John Clarke ([ORCID:0000-0003-3835-7761](https://orcid.org/0000-0003-3835-7761)), a researcher I know who studies NAFLD, told me the American Association for the Study of Liver Diseases (AASLD) is an authoritative source and has officially updated its nomenclature.

The AASLD points to publication of "A multi-society Delphi consensus statement on new fatty liver disease nomenclature" in Hepatology (https://pubmed.ncbi.nlm.nih.gov/37363821/). This exact article has been published across [multiple journals](https://pubmed.ncbi.nlm.nih.gov/?term=A+multi-society+Delphi+consensus+statement+on+new+fatty+liver+disease+nomenclature&sort=date&size=200), including the Journal of Hepatology (https://pubmed.ncbi.nlm.nih.gov/37364790/; _European_) and the Annals of Hepatology (https://pubmed.ncbi.nlm.nih.gov/37364816/; _international_). It seems there is consensus though there remains some controversy (example: https://pubmed.ncbi.nlm.nih.gov/37683734/).

The proposed changes involve revision of nomenclature _and_ definitions (with new definitions estimated to overlap with the old in 98% of cases). _I wonder_ if, given the revision of definitions, it would be **better to obsolete NAFLD and NASH** and to replace them with MASLD and MASH instead of simply making them synonyms?

Here's what the paper described as the new consensus:
1. Revise ‘fatty liver disease’ (DOID:9452)
    - Rename to 'steatotic liver disease'
    - Expand children to include all disease etiologies that cause hepatic steatosis including alcoholic, non-alchoholic (now 'metabolic dysfunction-associated’), viral, etc.
    - No official definition was given in this publication but it looks like most definitions for fatty liver disease describe it as having an intrahepatic fat ≥5% of liver weight.

2. Revise 'non-alcoholic fatty liver disease' (DOID:0080208)
    - As noted, MAFLD ('metabolic-associated fatty liver disease' OR 'metabolic dysfunction-associated fatty liver disease') was previously proposed and has been used in literature but it had a different definition and was not accepted as the consensus (https://pubmed.ncbi.nlm.nih.gov/37634892/). _We’ll probably want to include it as a synonym._
    - Rename to 'metabolic dysfunction-associated steatotic liver disease' (MASLD)
    - Re-define (summarized with help from https://pubmed.ncbi.nlm.nih.gov/37634892/):

> A steatotic liver disease characterized by hepatic steatosis in conjunction with at least one of five cardiometabolic risk factors (adjusted for age, sex and ethnicity), alcohol consumption below 140g/week (female) or 210g/week (male), and no other discernible cause. The five cardiometabolic risk factors are:
> 1. Body mass index≥ 25 kg/m2 (adult), 23 kg/m2 (adult Asian), or 85th percentile (pediatric); or waist circumference > 94 cm (adult male), 80 cm (adult female), or 95th percentile (pediatric).
> 2. Fasting serum glucose ≥ 5.6 mmol/L, 2-hr post-load glucose levels ≥ 7.8 mmol/L, glycated hemoglobin (HbA1c) ≥ 5.7% (39 mmol/L), type 2 diabetes, treatment for type 2 diabetes, previously diagnosed or treated type 2 diabetes (pediatric only), or serum glucose ≥ 11.1 mmol/L (pediatric only).
> 3. Blood pressure ≥ lower of 130/85 mmHg or 95th percentile (age < 13 years), or 130/85 mmHg (age ≥ 13 years); or specific hypertensive drug treatment.
> 4. Plasma triglycerides ≥ 1.15 mmol/L (age < 10 years) or 1.70 mmol/L (age ≥ 10 years); or lipid lowering treatment.
> 5. Plasma high-density lipoprotein cholesterol ≤ 1.0 mmol/L (adult male, pediatric) or 1.3 mmol/L (adult female); or lipid lowering treatment.

_This definition encompasses both MASLD & pediatric MASLD but maybe we should consider them two distinct diseases?_



3. Rename 'non-alcoholic steatohepatitis' (DOID:0080547) to 'metabolic dysfunction-associated steatohepatitis' (MASH)
    - No definition was included for MASH but the intent is that it keep the same relationship that NAFLD/NASH had so the definition doesn't need to change, only the parent.

4. Add a disease, exclusive of MASLD, for patients with combined etiology of MASLD & ALD, i.e. greater alcohol use with cardiometabolic risk factors.
    - New acronym ‘MetALD’
    - _New name was not clearly specified._ My guess at its intended name is either 'metabolic dysfunction- and alcohol-associated steatotic liver disease', based on the MAASLD acronym that was only avoided due to perception, or possibly 'metabolic dysfunction and alcohol-related liver disease', based on the name for ALD plus the newly included 'metabolic dysfunction' terminology.
    - Given the intention of the article and the spectrum of disease this is supposed to capture, this disease should probably be classified as a sibling of MASLD instead of a child.
    - A possible definition: 'A steatotic liver disease characterized by hepatic steatosis with at least one of the cardiometabolic risk factors for MASLD and alcohol consumption of 140-350g/week (females) or 210-420g/week (males).'
    - A few additional articles about MetALD:
        - https://pubmed.ncbi.nlm.nih.gov/37634892/ (uses name 'MASLD with increased alcohol intake'; used slightly for improving MASLD definition)
        - https://pubmed.ncbi.nlm.nih.gov/37592856/ (uses name 'MASLD + significant alcohol consumption')
        - https://pubmed.ncbi.nlm.nih.gov/37626604/

5. Add 'cryptogenic steatotic liver disease' (cryptogenic SLD) as a new disease grouping for patients with hepatic steatosis that do not have identifiable etiology and do not meet the criteria of other SLDs.
    - I'd probably add this a narrow synonym of 'steatotic liver disease' instead of as its own disease because 1) the DO has generally avoided the 'not otherwise specified' (NOS) disease categorizations, with ambiguous diseases generally being handled by the hierarchical graph structure, and 2) at some future point where all etiologies are identified, we would either need to keep 'crytogenic SLD' as a parent of those diseases to maintain tagged data linkages, or obsolete it and put a replace_by pointer to 'steatotic liver disease'.

Does the DO have a disease for alcohol-associated/related liver disease (ALD)? I couldn't find it, though I did see later progressions of the disease, i.e. 'alcoholic liver cirrhosis' (DOID:14018).

**Comment by sbello** [comment]
@allenbaron 
I think the existing definitions of NASH and NAFLD are sufficiently broad and vague that this update would be more of a refinement then an obsolete and replace. 

Agree with not adding the cryptogenic term. That sort of thing is why we have a generic parent that can be used in annotations.

While you are in there would you also please add nonalcoholic ... synonyms to the terms. Currently most just have non-alcoholic as the term label and often in the literature the non-hyphenated spelling is used. Having the alternate synonyms in there helps with search.

**Comment by allenbaron** [comment]
There may be updates needed to similar alcohol-associated diseases (e.g. 'alcoholic liver cirrhosis' (DOID:14018) and 'alcoholic hepatitis' (DOID:12351)) but these revisions have been implemented.

**Comment by allenbaron** [comment]
Linking to the [Curation_Review-Steatotic_liver_disease](https://docs.google.com/document/d/1-WYSRkuGVYTrz3KFcoQNQbSdeVY6opHy-jrRlioz-Yo/edit?tab=t.0#heading=h.byr91lu9t026) Google sheet that has related information, so everything is accessible from one place.

**Comment by allenbaron** [comment]
Question about “metabolic dysfunction-associated steatotic liver disease (DOID:0080208)” from Shur-Jen Wang (RGD; ORCID:0000-0001-5256-8683).

>It has its child term (non-alcoholic fatty liver (DOID:0080546)) as the exact synonyms:  NAFLD and non-alcoholic fatty liver disease, nonalcoholic fatty liver disease. Would  DO consider to remove NAFLD as synonyms for metabolic dysfunction-associated steatotic liver disease?

**Comment by allenbaron** [comment]
Hi Shur-Jen,
Thanks for reaching out. We're happy to make changes to improve the ontology.

“metabolic dysfunction-associated steatotic liver disease" (MASLD; DOID:0080208) was previously named "non-alcoholic fatty liver disease". The name was changed by an international consortium of liver clinicians in connection with a change to the definition that had minimal change to patient diagnosis (see the definition sources if you'd like details). The child term "non-alcoholic fatty liver" (NAFL; DOID:0080546) is a historical subtype that may not be in common use currently. We debated obsoleting it but chose to retain it to continue to distinguish MASLD which has an "absence of inflammation and hepatocyte injury" (and minimal clinical impact on patients) from the more severe form "metabolic dysfunction-associated steatohepatitis" (MASH; DOID:0080547), which was previously called NASH. The international consortium did not make a recommendation with regard to the term "non-alcoholic fatty liver" (NAFL), which is why we did not rename it.

Can you share the reasons behind the request to remove the NAFLD synonyms? Was that from confusion between NAFL and MASLD (previously NAFLD)? I'm totally open to thoughts you have about these diseases and welcome opinions on how we might improve them to better clarify things.

**Comment by allenbaron** [comment]
Hi Allen,

 

After considering the paragraph included in the email, we suggest to merge  (NAFL;DOID:0080546) to its parent (MASLD; DOID:0080208). The merging allows curators to use the parent term when no inflammation is involved rather than debating to use DOID:0080546 or DOID:0080208. We also suggest term editing after noticing that there is “metabolic dysfunction and alcohol associated liver disease (DOID:0070508)” under  steatotic liver disease parent. The red prints are suggestions for editing current DO terms. If they are not appropriate as terms in DO, then maybe they can be listed as synonyms. We appreciate your consideration.

 
![image](https://github.com/user-attachments/assets/7e648bd8-5114-4372-bc60-e7861f7adf3f)

Sincerely,\

**Comment by allenbaron** [comment]
Thanks for the reply Shur-Jen.

I think you're right about NAFL. I will plan to merge it into it's parent. In thinking about this, NAFL is really just "fatty liver" (which is an even higher parent in the DO) that no one could find a cause for (that was the prior exclusionary criteria for NAFLD). Also, NAFL doesn't exist in ICD-10 and was obsoleted in SNOMED CT and looking at the use of NAFL by the Alliance it's clear that there's been some confusion about what it refers to. Not to mention that NAFL is occasionally used interchangeably for NAFLD.

With regard to the name suggestions in red, all of these names were established by that international consortium of liver experts and I'm hesitant to change them. Our philosophy is to avoid creating new names for diseases whenever possible. We usually only add names that have not been used in the literature for grouping terms and, even then, we try to find an appropriate existing name. I think the expansion of disease names significantly contributes to the confusion of diseases. That's on top of the confusion that already exists in defining diseases (like in the example of NAFL / NAFLD above). 

Is the purpose of this request to avoid confusion between the terms?  I'm willing to add them as synonyms but would prefer to find a different solution if possible. It looks like the definition of 'metabolic dysfunction and alcohol associated liver disease' (MetALD; DOID:0070508) already includes a sentence meant to disambiguate these terms:

>A steatotic liver disease characterized by at least one of the five cardiometabolic risk factors for MASLD and alcohol consumption of 140-350g/week (females) or 210-420g/week (males). This disease is distinguished from MASLD by increased alcohol consumption and from ALD by the evidence of one or more of the MASLD cardiometabolic risk factors.


MetALD is a new disease defined to allow clinicians to better understand the intersection between MASLD and alcohol-associated liver disease (ALD; grouping term not in DO). Now that I'm looking at this again, I see that I didn't dig into the alcohol-associated liver disease updates by international consortia. We should probably add that as a grouping term.... I digress, sorry.


Do you think it would help to simplify the definitions further? I summarized the official definitions established by that international consortium but they are still somewhat complicated and long compared to the usual definitions in the DO. At the same time, it's difficult to define MASLD and MetALD without listing the cardiometabolic risk factors. What do you think of these definitions?

MASLD (DOID:0080208) - simplified the alcohol statement and the 5 risk factors

>A steatotic liver disease characterized by at least one of five specified cardiometabolic risk factors and no other discernible cause with normal to no alcohol use. The five cardiometabolic risk factors are: (1) higher than normal body mass index or waist circumference; (2) higher than normal serum glucose or glycated hemoglobin level, or type 2 diabetes; (3) higher than normal blood pressure or hypertensive treatment; (4) higher than normal plasma triglycerides or lipid lowering treatment; and (5) lower than normal plasma high-density lipoprotein cholesterol.


MetALD (DOID:0070508) - simplified the alcohol statement and added the five risk factors

>A steatotic liver disease characterized by at least one of five specified cardiometabolic risk factors and elevated alcohol consumption. This disease is distinguished from MASLD by increased alcohol consumption and from ALD by the evidence of one or more of the specified cardiometabolic risk factors. The five cardiometabolic risk factors are: (1) higher than normal body mass index or waist circumference; (2) higher than normal serum glucose or glycated hemoglobin level, or type 2 diabetes; (3) higher than normal blood pressure or hypertensive treatment; (4) higher than normal plasma triglycerides or lipid lowering treatment; and (5) lower than normal plasma high-density lipoprotein cholesterol.


Thanks for your time and input on this,
Allen

**Comment by allenbaron** [comment]
Hi Allen,

Thank you for your explanation. I am good with your concern and agree that synonyms are another source of confusion. We should use term definition to distinguish related terms or parent-child relationship. The existing definitions look good and I think it is a good idea to look into the alcohol-associated liver disease.

Thanks,
Shur-Jen
