### ISSUE TITLE
New synonym for Wolfram syndrome DOID:10632: WS

### ISSUE THREAD

**Issue by LaurensWilming** [DiseaseOntology/HumanDiseaseOntology#1282]
New synonym for Wolfram syndrome DOID:10632: 
**WS**
 See J:342760

**Comment by allenbaron** [comment]
Hi Laurens, we're happy to add an acronym for Wolfram syndrome. It looks like OMIM is using WFS and we have WFS1 and WFS2 for the children. Is WFS what you're looking for or is WS necessary? _Apologies, I can't follow the reference._

**Comment by allenbaron** [comment]
Just adding a note that we may need to revise DOID:0080584. It is currently named 'autosomal dominant Wolfram syndrome' while in OMIM and ORDO it's named '(autosomal dominant) Wolfram-like syndrome'. ORDO classifies it separately from Wolfram syndrome and not as a child. It is caused by the same gene as WFS1 (DOID:0110629) but has a different mode of inheritance (dominant not recessive) and slightly different phenotype (lack of cardiac and endocrine findings, diabetes insipidus). The current definition of Wolfram syndrome in DO is broad enough to include DOID:0080584. If we decide to keep it as is, we should at least add the 'Wolfram-like' synonym.

Also the definitions of WFS1 & WFS2 need to be updated to use the correct parent term.

**Comment by LaurensWilming** [comment]
> Hi Laurens, we're happy to add an acronym for Wolfram syndrome. It looks like OMIM is using WFS and we have WFS1 and WFS2 for the children. Is WFS what you're looking for or is WS necessary? _Apologies, I can't follow the reference._

Sorry, that's MGI's reference ID. It's PMID:37386014.
I guess adding WS as a synonym doesn't hurt.

**Comment by allenbaron** [comment]
Yeah, I think you're right. WS is also much more common in reference to Wolfram syndrome than WFS, though both are used. Both acronyms will be added to Wolfram syndrome in the next release.

This acronym is already in use for 'Werner syndrome' (DOID:5688) and having duplicate exact synonyms may affect some of our quality control tests but I don't think it will break anything. If somehow this causes issues at MGI (or elsewhere) please let us know.
