### ISSUE TITLE
Check Orphanet cross-references for Parkinson's disease

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1305]
**Is your request related to a specific disease? Please describe.**
Parkinson's disease (DOID:14330) and child terms

**Describe the proposed change(s)**
Parkinson's disease has the xref [ORDO:2828](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=2828) this is Young-onset Parkinson disease and this has the synonym 'Early-onset Parkinson disease'
Parkinson's disease in DO has a child term for 'early-onset Parkinson's disease' that is defined as prior to 50 years of age. This seems like a better match to the Orphanet term than the parent 

early-onset Parkinson's disease (DOID:0060894) has the Orphanet xref [ORDO:391411](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=391411) that is for Atypical juvenile parkinsonism

Atypical juvenile parkinsonism has OMIM xrefs  615528 (PARK19A, DOID:0060891) and 615530 (PARK20, DOID:0060898). There is a term for juvenile-onset Parkinson's disease (DOID:0060893) in DO. This term has no xrefs

DOID:0060891 has xref  [ORDO:391411](http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=391411)

juvenile-onset Parkinson's disease (DOID:0060893), PARK19A (DOID:0060891), and PARK20 (DOID:0060898) are currently siblings in DO

I would suggest

- remove ORDO:2828 as an xref to DOID:14330 and make it an xref to DOID:0060894
- remove ORDO:391411 as an xref to DOID:0060894
- review the relationship between juvenile-onset Parkinson's disease (DOID:0060893), PARK19A (DOID:0060891), and PARK20 (DOID:0060898), should these be child terms to juvenile onset instead of siblings?
- review the relationship between the DO term juvenile-onset Parkinson's disease and the Orphanet term Atypical juvenile parkinsonism, are these the same thing? Or should DO add a new term for Atypical juvenile parkinsonism and make PARK19A and PARK20 child terms to this?

**Comment by csbjohnson** [comment]
Thank you very much for your request, Sue (@sbello). We will review your request. Wishing you a wonderful rest of your day!

Best,
Claudia Marie Sánchez-Beato Johnson

**Comment by lschriml** [comment]
--> reviewed and updated DOID to Orphaned ID xref mappings 

for Early-onset Parkinson disease'
     added synonym: Young-onset Parkinson disease

-- early-onset Parkinson's disease (DOID:0060894) has Orphanet xref [ORDO:391411] that is for Atypical juvenile parkinsonism
        --> this Orphaned ID is annotated on Parkinson's disease 19A DOID:0060891
              this is: [OMIM:615528](http://www.omim.org/entry/615528)

Interesting that Orphaned is using "Parkinsonism' rather than "Parkinson's" 

for: 
Atypical juvenile parkinsonism (ORPHA:391411) 
definition: A complex form of young-onset Parkinson disease that manifests with pyramidal signs, eye movement abnormalities, psychiatric manifestations (depression, anxiety, drug-induced psychosis, and impulse control disorders), intellectual disability, and other neurological symptoms (such as ataxia and epilepsy) along with classical parkinsonian symptoms.

--Mapping to Parkinson's 19A and 20 subtypes in OMIM 
--> For now, I would stick with OMIM's subtyping, rather than Orphanet's, which seems to be in progress.
    The atypical term seems to be an interim term that they devised.

Cheers,
Lynn
