### ISSUE TITLE
Please revert change of DOID:0050156 

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1341]
**Is your request related to a specific disease? Please describe.**
[DOID:0050156](http://www.disease-ontology.org/?id=DOID:0050156)
Was 'idiopathic pulmonary fibrosis' is now 'interstitial lung disease 2'

The definition was "A pulmonary fibrosis that is characterized by scarring of the lung." 
The definition is now " An interstitial lung disease pulmonary fibrosis that is characterized by scarring of the lung and that has_material_basis_in heterozygous mutation in the SFTPA2 gene on chromosome 10q22."

The change in definition has significantly narrowed the meaning of the term and renders many existing annotations incorrect as these are not specific for lung fibrosis caused by SFTPA2 or its homologs.

**Describe the proposed change(s)**
Please revert the definition to its prior definition and create a new entry for "interstitial lung disease 2".  The OMIM xref could then be moved. 

**References**
Please see https://www.alliancegenome.org/disease/DOID:0050156 for the many existing references for models of or markers for pulmonary fibrosis.

**Comment by allenbaron** [comment]
Thanks Sue, we'll restore the previous definition and add a new term to match OMIM's changes.

@csbjohnson, do you mind addressing this issue? It will probably require checking other xrefs to make sure they are on the most appropriate term. Feel free to ask if you have questions.

**Comment by allenbaron** [comment]
I'm looking at this a little more closely and noticed that the previous definition of 'idiopathic pulmonary fibrosis' (IPF) in the DO did not differentiate it in any way from it's parent 'pulmonary fibrosis'. It doesn't seem to be well differentiated from it's siblings either. It seems to me an IPF could also be diffuse, localized, or postinflammatory. The definitions are overlapping and non-distinguishing but, based on what I read in OMIM's record, it appears that IPF has a specific presentation and is considered a disease or set of diseases; more defined than the term 'idiopathic' would normally imply.

I'd suggest we follow @sbello's course of action and also update IPF's definition to clarify how it differs from 'pulmonary fibrosis'. I assume it should also be restored as a child of 'pulmonary fibrosis'. I think whether it should or not would become apparent after determining how to modify the definition. 

As part of this definition update, I think it might also be worth reviewing how the Alliance has been using these diseases. Among pulmonary fibrosis and it's children in the DO, the Alliance has annotated only to 'pulmonary fibrosis' and IPF. I'm not sure how to approach this exactly since there are a lot of annotations (~1,000 in genes, alleles, and models). I think the main thing to determine would be if the Alliance has been annotating to the general idea of "this is an idiopathic disease" or to the more specific meaning of IPF as a disease name, as the OMIM record suggests (hoping my meaning is understood here). My reasoning here is that we want to avoid invalidating hundreds of annotations and update the definition consistent with its current use.

**Comment by sbello** [comment]
Thanks @allenbaron I was wondering the same thing, how does idiopathic PF differ from PF? The definitions did not make it clear.

The issue in the Alliance isn't quite as bad as it looks, many of the annotations are 'inferred via orthology' if you limit it to direct annotations (is marker for, is implicated in association types) there are around 150. Still more than I want to clean up. 

The 2 models in MGI of IPF (https://www.informatics.jax.org/disease/DOID:0050156) specifically compare the mouse models to human IPF patients and were therefore curated to IPF rather than PF.

These define IPF as 
"Idiopathic pulmonary fibrosis is a group of usually fatal disorders of the lung characterized by an alveolitis which progresses
to interstitial fibrosis (1)" PMID:7542280

"Pulmonary fibrosis is a common and usually fatal end-stage condition of various lung diseases characterized by interstitial
pneumonia and scarring. Inflammation is an important contributor in some subtypes of pulmonary fibrosis that have been
associated with autoimmune diseases such as systemic sclerosis. However, the etiology is unknown in most cases, which are
therefore classified as idiopathic pulmonary fibrosis (IPF) or nonspecific interstitial pneumonia (NSIP) (6)." PMID:18641127

**Comment by lschriml** [comment]
https://www.lung.org/lung-health-diseases/lung-disease-lookup/idiopathic-pulmonary-fibrosis#:~:text=Idiopathic%20pulmonary%20fibrosis%20(IPF)%20is,makes%20it%20difficult%20to%20breathe.

Idiopathic pulmonary fibrosis (IPF) is the most common type of pulmonary fibrosis. 
t is a disease that causes scarring (fibrosis) of the lungs. The word "idiopathic" means it has no known cause. Scarring causes stiffness in the lungs and makes it difficult to breathe.

**IPF references:**
https://www.ncbi.nlm.nih.gov/books/NBK448162/

https://www.nhlbi.nih.gov/health/idiopathic-pulmonary-fibrosis

**PF references:**
https://www.lung.org/lung-health-diseases/lung-disease-lookup/pulmonary-fibrosis
      -- Pulmonary fibrosis is scarring of the lungs. 
      -- Pulmonary fibrosis is an interstitial lung disease. Interstitial lung diseases are a group of conditions that cause inflammation and scarring around the tiny air sacs (alveoli) in the lungs.
         -- Inhaling hazardous chemicals can be one cause of pulmonary fibrosis. PF can also be caused by certain diseases, medication and genetics. Most often the cause is unknown. This is called idiopathic pulmonary fibrosis (IPF).

**Comment by csbjohnson** [comment]
Add sources and metadata to both entities- Idiopathic pulmonary fibrosis and Pulmonary fibrosis
