### ISSUE TITLE
Polycystic liver disease subtypes

### ISSUE THREAD

**Issue by csbjohnson** [DiseaseOntology/HumanDiseaseOntology#1351]
Phenotypic Series - PS174050

**Comment by allenbaron** [comment]
Since these are subtypes of polycystic liver disease I think it makes sense to make them children of the existing 'polycystic liver disease' (DOID:0050770).

Also, the MIM xref on DOID:0050770 (and possibly others) is to POLYCYSTIC LIVER DISEASE 1. When adding genetic subtypes to an existing disease that _lacks a genetic cause in the definition_, its best practice to keep that definition as is, since annotations may be to varying genetic causes, and to create a new disease subtype for each genetic cause, moving xrefs to these subtypes as appropriate. In this case, that means the new 'polycystic liver disease 1' subtype also needs to be created and all the xrefs that specify the genetic cause equivalent to that should be moved to this subtype. Then, xrefs to grouping terms in OMIM (i.e. the phenotypic series) and other clinical vocabularies, where it exists, should be added to the original 'polycystic liver disease' (DOID:0050770).

**Comment by allenbaron** [comment]
Also note that "with or without" phrases should be excluded in DO disease names (they can be added as synonyms). The only exception would be if they are absolutely necessary to distinguish one disease from another, and I am not aware of any instances where this applies.

My apologies that this info wasn't included in [my curation notes](https://docs.google.com/document/d/15bmqqTJP8YIQzSIO0Aa8PUj7JCYBIvEc6HJxTNz5LHA/edit). I've added it now.
