### ISSUE TITLE
Add APLAID (OMIM 614878)

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1387]
Please add a new disease term
autoinflammation, antibody deficiency, and immune dysregulation syndrome (OMIM label)

Def: An autoimmune disease characterized by recurrent blistering skin lesions with a dense inflammatory infiltrate and variable involvement of other tissues, including joints, the eye, and the gastrointestinal tract that has_material_basis in heterozygous mutation in PLCG2 on chromosome 16q23.
def xref - PMID:23000145 (https://pubmed.ncbi.nlm.nih.gov/23000145/)

Not sure that autoimmune disease is the best parent, would be good to double check this. The Orphanet parent is Mixed autoinflammatory and autoimmune syndrome

 
synonyms
autoinflammation-PLCG2-associated antibody deficiency-immune dysregulation (Orphanet and Gard label)
APLAID (OMIM and Orphanet)
AUTOINFLAMMATION, ANTIBODY DEFICIENCY, AND IMMUNE DYSREGULATION, PLCG2-ASSOCIATED  (OMIM)

xref:
MIM:614878
ORDO:324530
GARD:17486

Mouse model in PMID:36997670

**Comment by allenbaron** [comment]
Looking into parentage I noticed that this has overlapping features and is allelic to 'familial cold autoinflammatory syndrome 3' (commonly called PLAID; DOID:0090064). That is a descendant of 'primary immunodeficiency disease' (DOID:612), which has the definition:
>An immune system disease that results when one or more essential parts of the immune system is missing or not working properly at birth due to a genetic mutation.

_The "not working properly" portion of the definition of primary immunodeficiency disease may be open for misinterpretation._

Immune deficiency does appear to be a feature of APLAID (respiratory infections are common[^1]), as it is for PLAID. So, 'primary immunodeficiency disease' (DOID:612) would probably be a better parent than autoimmune disease.

Another option, which might be better still, would be to add 'autoinflammatory disease' as a new grouping term. I usually want to avoid new grouping terms but I think it's warranted in this case.

'autoinflammatory disease' is defined as:
>Autoinflammatory diseases refer to problems with the innate immune system’s reactions. Immune cells target the body’s own healthy tissues by mistake, signaling the body to attack them. This can cause intense episodes of inflammation that result in such symptoms as fever, rash, or joint swelling. These diseases also carry the risk of amyloidosis, a potentially fatal buildup of a blood protein in vital organs.[^2]

The autoinflammatory diseases mentioned by NIAMS[^2] include:
- Familial Mediterranean Fever
- Neonatal Onset Multisystem Inflammatory Disease
- Tumor Necrosis Factor Receptor-Associated Periodic Syndrome
- Deficiency of the Interleukin-1 Receptor Antagonist
- CANDLE = DOID:0060913 (parent = syndrome)

The immune deficiency of APLAID appears to be minimal compared to the over-active innate immune response. The FACS diseases could be classified as autoinflammatory diseases, as could 'familial Behcet-like autoinflammatory syndrome' and I would venture to guess that a number of other diseases could be as well. It seems that vague statement in primary immunodeficiency has been used to make it a grouping parent for autoinflammatory diseases, which may not have any real immunodeficiency.

@lschriml, thoughts?

[^1]: Zhou Q, Lee GS, Brady J, Datta S, Katan M, Sheikh A, Martins MS, Bunney TD, Santich BH, Moir S, Kuhns DB, Long Priel DA, Ombrello A, Stone D, Ombrello MJ, Khan J, Milner JD, Kastner DL, Aksentijevich I. A hypermorphic missense mutation in PLCG2, encoding phospholipase Cγ2, causes a dominantly inherited autoinflammatory disease with immunodeficiency. Am J Hum Genet. 2012 Oct 5;91(4):713-20. doi: 10.1016/j.ajhg.2012.08.006. Epub 2012 Sep 20. PMID: 23000145; PMCID: PMC3484656. https://pubmed.ncbi.nlm.nih.gov/23000145/
[^2]: National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS). Health Topics, Autoinflammatory Diseases. https://www.niams.nih.gov/health-topics/autoinflammatory-diseases

**Comment by allenbaron** [comment]
I've opened a new ticket to consider adding 'autoinflammatory disease' (#1400).

In the mean time, I will classify this disease as a child under 'primary immunodeficiency disease' (DOID:612) since that is where the allelic disease 'familial cold autoinflammatory syndrome 3' (commonly called PLAID; DOID:0090064) is located and Zhou et al[^1], who identified the disease requested in this issue stated:
>In a broad sense, autoinflammatory diseases could be defined as primary immunodeficiencies because they result from defects in components of the innate immune response.

[^1]: Zhou Q, Lee GS, Brady J, Datta S, Katan M, Sheikh A, Martins MS, Bunney TD, Santich BH, Moir S, Kuhns DB, Long Priel DA, Ombrello A, Stone D, Ombrello MJ, Khan J, Milner JD, Kastner DL, Aksentijevich I. A hypermorphic missense mutation in PLCG2, encoding phospholipase Cγ2, causes a dominantly inherited autoinflammatory disease with immunodeficiency. Am J Hum Genet. 2012 Oct 5;91(4):713-20. doi: 10.1016/j.ajhg.2012.08.006. Epub 2012 Sep 20. PMID: 23000145; PMCID: PMC3484656.

**Comment by allenbaron** [comment]
This disease will be in the release as DOID:0070615 with the name from OMIM as the primary label. The acronym is also included and the original name as proposed by the authors (since that's where the acronym derived from) but _not_ the additional synonyms at OMIM or Orphanet since they have not yet appeared in literature and are unlikely to.
