### ISSUE TITLE
Differences between ontology versions

### ISSUE THREAD

**Issue by mbernste** [DiseaseOntology/HumanDiseaseOntology#241]
Hi,

I noticed that there are differences between the OBO file ontology releases here in the GitHub repository and the OBO files at the OBOFoundry website.

For example, the term "lung adenocarcinoma" has an "is_a" edge to "adenocarcinoma" in the 1-13-17 release file here, but not in the OBOFoundry.  It seems the versions in this repository are more comprehensive.

I am wondering where I should look to find the most comprehensive, up-to-date version of the ontology's OBO file.  I ask, because I am working on a data annotation tool that, ideally, will automatically download the latest ontology.

Thanks,
Matt

**Comment by elviram** [comment]
Hello Matt,

the DO file you get at the purl from the OBOFoundry website is the doid-non-classified.obo. This version of DO has a single is_a hierarchy.
The doid.obo file at the repo here is the one with multiple is_a edges due to it being run through a reasoner (in it's OWL format) and then converted to OBO.
So long story short, the doid.obo file here is the "most comprehensive". 
Did that clear it up?

Best,
Elvira

**Comment by mbernste** [comment]
Thanks! That clears things up.
