### ISSUE TITLE
hairy cell leukemia of spleen VS. splenic manifestation of hairy cell leukemia

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#246]
Are these two terms equivalent?

http://purl.obolibrary.org/obo/DOID_10265
http://purl.obolibrary.org/obo/DOID_709

**Comment by lschriml** [comment]
Hello Gregory, 
  thank you for pointing these out. 

Taking a look, to see the history of these disease names and their current usage. 
It looks like they are the same disease, and that they were created when some vocabularies used the one name (hairy cell leukemia of spleen), while others used splenic manifestation of hair cell leukemia. 
   The splenic form -- this occurs during the course of hairy cell leukemia, when some of the leukemia cells collect in the spleen and cause swelling. 

    **hairy cell leukemia of spleen** (DOID:10265) is no longer found in ICD9CM
--> I will merge this term into **splenic manifestation of hairy cell leukemia**
  
           NCI:   Splenic Manifestation of Hairy Cell Leukemia (Code C7301)
                   has two parents in NCI (leukemia and spleen neoplasms). 

I would conclude that this is a spleen cancer, not a type of leukemia (rather it is caused by the accumulation of leukemia cells in the spleen. 

I will keep: 
   splenic manifestation of leukemia as a child of spleen cancer
      and  
        remove the parent (hairy cell leukemia) from splenic manifestation of hair cell leukemia
and 
       remove the parent prolymphocytic leukemia from splenic manifestation of prolymphocytic leukemia 

Cheers,
Lynn
