### ISSUE TITLE
pituitary neoplasms

### ISSUE THREAD

**Issue by cmungall** [DiseaseOntology/HumanDiseaseOntology#247]
```
   is_a DOID:162 ! cancer
    is_a DOID:0050686 ! organ system cancer
     is_a DOID:170 ! endocrine gland cancer
      is_a DOID:1785 ! pituitary cancer
       is_a DOID:5716 ! hormone producing pituitary cancer
        is_a DOID:5396 ! prolactin producing pituitary tumor *** xref: NCIT:C7910
        is_a DOID:6256 ! malignant growth hormone secreting neoplasm of pituitary
        is_a DOID:6274 ! malignant thyroid stimulating hormone producing neoplasm of pituitary gland
        is_a DOID:6276 ! malignant ACTH producing neoplasm of pituitary gland
```

this is problematic as it assumes the marked term is a cancer. It is xreffed the the NCIT malignancy-neutral Neoplasm. See also: https://github.com/monarch-initiative/monarch-disease-ontology/issues/170

Looking at pituitary neoplasms in general in DOID:

![image](https://cloud.githubusercontent.com/assets/50745/22400085/a0f45046-e560-11e6-996b-caba68408e2a.png)

We can see two separate branches with no grouping into a malignancy-neutral pituitary neoplasm as we have in NCIT.

Here is NCIT. Why not just adopt it directly?

![image](https://cloud.githubusercontent.com/assets/50745/22400091/eb9f8e80-e560-11e6-8bec-012660e902dd.png)

**Comment by lschriml** [comment]
Thank you for looking at this area of the DO.
One important thing to note, NCI often includes both malignant and benign forms of a cancer under the same NCI record. The DO separates these two forms, creating unique DOIDs. Therefore, DO may have two DOIDs mapped to one NCI record.

Regarding pituitary neoplasms: 
  NCI's: (Code C7910)  Prolactin-Producing Pituitary Gland Neoplasm
  Definition: An adenoma or carcinoma of the anterior lobe of the pituitary gland that produces prolactin.
  --> This is a case where both the benign (adenoma) and malignant (carcinoma) are included in one NCI record (per the definition)
 --> NCI also has a record for the Ademona:
    Prolactin-Producing Pituitary Gland Adenoma (Code C3342)
So, in DO:
   --> NCI's: (Code C7910)  Prolactin-Producing Pituitary Gland Neoplasm -- is classified as a cancer
   and
--> NCI's (Code C3342) is the Adenoma, DO's name: prolactinoma 

For DO: 
   As the cancer term is referring to a carcinoma rather than just the cancer, 
I am revising it's parentage: (DOID:5396) to be a child of pituitary carcinoma. 

Cheers,
Lynn
