### ISSUE TITLE
xrefs for superficial mycosis

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#338]
The mesh and umls xrefs for [superficial mycosis](http://purl.obolibrary.org/obo/DOID_0050133) don't seem right.
https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C2980104
https://ncim-stage.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0031898
https://meshb.nlm.nih.gov/record/ui?ui=D010854

**Comment by lschriml** [comment]
superficial mycosis == piedra    (synonyms)
   superficial mycosis is the more up to date nomenclature 
the MeSH term is for piedra 
     https://www.ncbi.nlm.nih.gov/mesh/D010854

--> we don't have any NCI xrefs for this term.
Searching NCI metathesaurus, this DO term is a synonym of https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=C0011630

--> however, we link to NCI thesaurus (cancer terms only), 
rather than the broader NCI metathesaurus

--> I reviewed and cleaned up the SNOMED IDs
