### ISSUE TITLE
NTR hyperferritinemia-cataract syndrome  OMIM# 600886 

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#379]
Congenital nuclear cataract and elevated serum ferritin not related to iron overload  usually transmitted as an autosomal dominant trait. Known to be caused by mutations in iron storage protein FTL (ferritin, light polypeptide).

**Comment by lschriml** [comment]
Thank you for the term request !!
I will take a look.
Cheers,
Lynn

**Comment by lschriml** [comment]
NTR hyperferritinemia-cataract syndrome 
OMIM# 600886 
      HYPERFERRITINEMIA WITH OR WITHOUT CATARACT

https://ghr.nlm.nih.gov/condition/hyperferritinemia-cataract-syndrome

Hyperferritinemia-cataract syndrome is a disorder characterized by an excess of an iron storage protein called ferritin in the blood (hyperferritinemia) and tissues of the body. A buildup of this protein begins early in life, leading to clouding of the lenses of the eyes (cataracts). 

Hyperferritinemia-cataract syndrome is caused by mutations in the FTL gene. This gene provides instructions for making the ferritin light chain, which is one part (subunit) of the protein ferritin.

Synonyms
Bonneau-Beaumont syndrome
hereditary hyperferritinemia-cataract syndrome
hereditary hyperferritinemia with congenital cataracts


https://rarediseases.org/rare-diseases/hyperferritinemia-cataract-syndrome/

**Comment by sbello** [comment]
On OMIM spreadsheet https://docs.google.com/spreadsheets/d/10cE_2fGyEW1B2r_6yeIYqeTMbYmpmdwflamf7aGbUm0/edit?usp=sharing

**Comment by sbello** [comment]
added DOID:0111256
