### ISSUE TITLE
superior semicircular canal dehiscence syndrome

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#380]
Synonyms:
canal dehiscence syndrome
superior canal syndrome
third mobile window syndrome
minor’s syndrome
SSCD

is_a syndrome   DOID:225
may also be a disease of anatomical entity  DOID:7  
The anatomical entity would be the semicircular canal or the ear.
 

Definition:
The absence of bone overlying the superior semicircular canal facing toward the dura of the middle cranial fossa. The most common symptoms are vertigo/dizziness elicited by pressure altering activity, Tullio’s phenomenon (sound-induced vertigo), fullness/pressure in the ear and autophony.  Autophony is hearing internal noises louder than would be expected, such as hearing your eyes move/blink, heart beat or joint movements.  Hearing loss and fluctuating hearing loss can occur, mimicking otosclerosis or Meniere’s disease.  Fullness in the ear and hearing your breathing loudly in the ear are symptoms of Patulous Eustachian Tube, but can also be found with SSCD.  Finally, most patients with the anatomic defect of superior semicircular canal dehiscence have no symptoms at all for some time prior to developing symptoms.

https://rarediseases.org/rare-diseases/superior-semicircular-canal-dehiscence/
PMID: 9525507

See the phenotype request at 
https://github.com/obophenotype/mammalian-phenotype-ontology/issues/2313 

ORCID:0000-0002-2244-7917
GOC:CVS
&
ORCID: 0000-0003-3311-7320
ZFIN:KS @kevinschaper

**Comment by lschriml** [comment]
https://en.m.wikipedia.org/wiki/Superior_canal_dehiscence

Superior canal dehiscence (SCDS) is a rare medical condition of the **inner ear,** leading to hearing and balance symptoms in those affected.[1][2][3] The symptoms are caused by a thinning or complete absence of the part of the temporal bone overlying the superior semicircular canal of the vestibular system

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5375705/

http://www.hopkinsmedicine.org/otolaryngology/research/vestibular/recent_findings.html

**Comment by lschriml** [comment]
added
