### ISSUE TITLE
Xrefs added by Wikidata users (Robot Template)

### ISSUE THREAD

**Issue by stuppie** [DiseaseOntology/HumanDiseaseOntology#463]
Below is a robot template for adding all xrefs that have been added by Wikidata users on all diseases items

https://docs.google.com/spreadsheets/d/1U5Y10Rr5MCQY2YIBvu4AsOtASYp7NppP-5dHKrGx8GY/edit?usp=sharing

**Comment by stuppie** [comment]
I'm not sure how to make a robot template for removing things, but there's only a couple, so I'm just pasting them here



ID | A rdfs:label | CLASS_TYPE | xrefs | QID
-- | -- | -- | -- | --
DOID:1442 | Alpers syndrome | equivalent | OMIM:203700 | https://www.wikidata.org/wiki/Q2028015
DOID:0060312 | angular cheilitis | equivalent | UMLS_CUI:C0007971 | https://www.wikidata.org/wiki/Q1456558
DOID:1627 | intraductal papilloma | equivalent | UMLS_CUI:C0206713\|NCI:C3785\|MESH:D018300 | https://www.wikidata.org/wiki/Q6058395
DOID:4166 | syphilis | equivalent | MESH:D002601 | https://www.wikidata.org/wiki/Q41083
DOID:0050865 | tongue squamous cell carcinoma | equivalent | UMLS_CUI:C0007137 | https://www.wikidata.org/wiki/Q28757362
DOID:0090106 | Bh4-deficient hyperphenylalaninemia A | equivalent | MESH:C535325 | https://www.wikidata.org/wiki/Q4641554
DOID:446 | primary hyperaldosteronism | equivalent | MESH:D003480\|UMLS_CUI:C0010481\|NCI:C2969 | https://www.wikidata.org/wiki/Q1640860
DOID:6713 | cerebrovascular disease | equivalent | MESH:D020521\|NCI:C3390\|UMLS_CUI:C0038454\|UMLS_CUI:C0007820\|OMIM:601367\|NCI:C2938 | https://www.wikidata.org/wiki/Q3010352
DOID:0060119 | pharynx cancer | equivalent | MESH:D010610\|UMLS_CUI:C0031347\|NCI:C3325 | https://www.wikidata.org/wiki/Q2085187

**Comment by lschriml** [comment]
Thank you Greg,
 going over this list.
 
**Alpers syndrome**
OMIM:203700 is correctly assigned to Alpers syndrome (synonym: MITOCHONDRIAL DNA DEPLETION SYNDROME 4A) 
http://omim.org/entry/203700?search=203700&highlight=203700

UMLS_CUI:C0007971
   -- this xref is associate with the parent term, cheilitis rather than angular cheilitis 

**intraductal papilloma**
UMLS_CUI:C0206713|NCI:C3785|MESH:D018300
   the MeSH ID is correct,   https://meshb.nlm.nih.gov/record/ui?ui=D018300
  UMLS CUI is correct, http://medical-language-international.com/index-umls.php?C0206713
 NCI is correct: https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=16.12d&ns=NCI_Thesaurus&code=C3785

**syphilis**: updated MeSH term to D013587

**tongue squamous cell carcinoma** - in DO
   has UMLS_CUI:C0349566. 
see: SCC of the Tongue
http://www.medindex.am/glossary/semantic_types/B2.2-disease-syndrome-pathologic-function.php
        UMLS_CUI:C0007137 = squamous cell carcinoma


**primary hyperaldosteronism**
MESH:D003480. --> Cushing syndrome (same disease)
UMLS_CUI:C0010481
NCI:C2969

**cerebrovascular disease**. == Stroke    --> This DO term includes these other 'merged' DOIDs
MESH:D020521
NCI:C3390 = Cerebrovascular Accident
UMLS_CUI:C0038454
UMLS_CUI:C0007820
OMIM:601367. == Stroke 
NCI:C2938 =   Cerebrovascular Disorder (same disease)
--

**pharynx cancer**
MESH:D010610 == Pharyngeal Neoplasms
UMLS_CUI:C0031347
NCI:C3325 == Pharyngeal Neoplasm. (same disease)

**Comment by lschriml** [comment]
Thank you Greg for the xrefs, we will review. 
Lynn

**Comment by lschriml** [comment]
Thank you Greg !!

**Comment by stuppie** [comment]
OMIM:
https://docs.google.com/spreadsheets/d/1NMDWomzQzjFwL_9B-3up0qSKzqmmTg_Orrqt-pQg0vU/edit?usp=sharing

**Comment by stuppie** [comment]
ORDO:
https://docs.google.com/spreadsheets/d/1IRjsBk2FgiFC-6dBpJJB1hu7BI8WpovibV0b0eLjdhk/edit?usp=sharing

**Comment by stuppie** [comment]
Updating this issue with MeSH xrefs that are added by Wikidata users, using the most recent DO release (2018-07-05). I've also added another column showing if that xrefs is already present on another item. It is also split on xrefs where the label or synonym string matches, versus not.
https://docs.google.com/spreadsheets/d/1f_TdrI3jHtSB-XdBRHZot4yFJl__MLvKZmOjBvavMro/edit?usp=sharing

**Comment by stuppie** [comment]
Updated the same google sheet with GARD

**Comment by lschriml** [comment]
Super, thank you !! 

I’m working my way through the MeSH terms.
Making notes in the spreadsheet.

Cheers,
Lynn

**Comment by lschriml** [comment]
All of the xrefs were reviewed and added to DO.
