### ISSUE TITLE
nephrotic syndrome

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#503]
DO currently has the terms nephrotic syndrome (DOID:1184) and familial nephrotic syndrome (DOID:2590). Both lack definitions. The OMIM IDs for the phenotypic series PS256300 are xrefs for nephrotic syndrome in DO but are xrefs to Familial idiopathic steroid-resistant nephrotic syndrome (ORDO:656) in Orphanet. ORDO:656 is not an xref in DO but we may want to add children to familial to group steroid-resistant and steroid-sensitive forms.  Despite Orphanet grouping all the OMIM IDs to steroid-resistant I'm not sure this is accurate as the OMIM summary for 256300 indicates that only 20% of patients are steroid resistant. I think the OMIM IDs should end up being xrefs to children of DOID:2590 (once I'm done splitting these out) or possibly to the resistant and sensitive clumps if that proves to be a viable strategy. 

I'll update this as I work through the OMIM terms.

I would suggest the following for definitions for the existing DO terms
DOID:1184 - A nephrosis characterized by marked increase in glomerular protein permeability resulting in marked elevation of urine protein levels, hypoalbuminemia, hyperlipidemia, and hypercoagulability.
references: ISBN:0-8036-0654-0|url:https://en.wikipedia.org/wiki/Nephrotic_syndrome 

DOID:2590 - Is there a standard way in definitions to distinguish familial from spontaneous occurrence of a disease?

**Comment by sbello** [comment]
I've added the terms to the OMIM series split ROBOT spreadsheet. I've colored yellow those that are known to be steroid resistant. The light yellow one has at least one case that is steroid sensitive but most are steroid resistant. We may want to add a steroid-resistant DO class to group this set. This could have ORDO:656 as an exact cross-reference.

I've also added definitions for nephrosis and nephrotic syndrome. 

I'm still not sure how to define "familial nephrotic syndrome"

**Comment by lschriml** [comment]
Hello Sue,
 I have reviewed this set of terms.
Added the definitions for nephrosis and nephrotic syndrome.

--> other than the term name, there is not a way to distinguish the familial and spontaneous forms. 

--I have marked the rows in the split file for this set of terms as reviewed, ready for loading. 

-- for the familial form:   OMIM:PS256300
I think this should be the parent term for the OMIM subtypes to distinguish them from nephrotic syndrome due to non-genetic causes.
Reference: https://www.ncbi.nlm.nih.gov/pubmed/19066979

I have updated the ROBOT template 
https://docs.google.com/spreadsheets/d/1wb6bZ2wIUuq-yOBhCXrMcuy7meHoq_Xr2OtzaUbyKnc/edit#gid=1758987659

Cheers,
Lynn

**Comment by groliver** [comment]
I would also recommend putting nephrotic disorder under the proteinuria category

**Comment by lschriml** [comment]
Agreed, 
I will make nephrosis a child of proteinuria.

    proteinuria: the presence of excess protein in the urine

Cheers,
Lynn

**Comment by lschriml** [comment]
Done
