### ISSUE TITLE
hypothalamic disease (DOID:1931) wrong parent term

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#534]
Current parent terms:

is_a: DOID:0080001 ! bone disease
is_a: DOID:4662 ! thalamic disease

I believe, [bone disease] parent is a mistake. MESH lists [brain disease] as a parent.

Btw, I was using https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/releases/2018-06-25/doid.obo file. However, the ontology browser at http://disease-ontology.org/ for [hypothalamic disease] term is showing [brain disease] as the parent. So, how can I find the file that the ontology browser is using? And how can I explain the discrepancies between the release file and what I see in the browser?

Thank you,
Marek

**Comment by lschriml** [comment]
Hello Marek,
 Apologies for the confusion. 

Currently our file updates are ahead of our web site update.
We are pushing the latest release to our website today.
The DO website uses our doid-non-classified.obo file. 
The OLS at EBI uses our doid.owl file.
    They update every time we push a new commit in GitHub. 

We are developing an additional view of our website to also show this OWL view. 

We create DO releases every two weeks (although this varies a bit currently).

Day to day, we edit our src/ontology/doid-edit.owl file.

This morning I did some further updates to the files in our src/ontology directory.

This is always the most up-to-date version of a DO file. 
—> I recommend looking at these files. 

The differences you are seeing are due to synching between the release and the website. 

Cheers,
Lynn

**Comment by tutajm** [comment]
Thank you for the info. It is very helpful!

Marek

**Comment by lschriml** [comment]
Fixed
