### ISSUE TITLE
typo in definition for DOID:0070002

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#575]
The definition for DOID:0070002 has an odd character between 'has_material_basis_in' and 'homozygous' in it that causes display issues on MGI and the Alliance web pages (https://build.alliancegenome.org/disease/DOID:0070002).

**Comment by sbello** [comment]
Same issue in DOID:0070000

**Comment by lschriml** [comment]
Hello Sue,
 I've opened these in Protege (doid-edit.owl), I am only seeing a space between the RO term and homozygous. Also checked the doid-merged.owl file. 
I deleted the space and added it back.

I have also fixed the RO in the text definitions for this group of DO terms,
so that has_material_basis_in has the under scores.

Can you try that for your file ? 

Cheers,
Lynn

**Comment by sbello** [comment]
This is something we often see with hidden characters that came in through a copy/paste. I would expect that deleting and then re-adding the space should fix this. This is not the sort of thing that would require an immediate fix on our end so we can wait for the next DO release before updating the files on our end. While I could modify the files on our end I don't have a way to push the modified files through the load process without taking up a bunch of software engineer time for multiple SE's and without doing that I can't see if the fix did anything.   I think we can wait and after the next release I'll see if this is fixed.

**Comment by lschriml** [comment]
Thank you Sue !! 
Cheers,
Lynn
