### ISSUE TITLE
NTR PAPA syndrome

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#630]
PAPA (pyogenic arthritis, pyoderma gangrenosum and acne) syndrome is caused by mutations in PSTPIP1 (also known as CD2BP1).

PMID: 21532836

is_a DOID:612

OMIM: 604416

**Comment by lschriml** [comment]
Added !! 

PAPA syndrome is an acronym for pyogenic arthritis, pyoderma gangrenosum and acne. It is a rare genetic disorder characterised by its effects on skin and joints.
 inherited in an autosomal dominant fashion

https://en.wikipedia.org/wiki/PAPA_syndrome

https://rarediseases.info.nih.gov/diseases/9176/pyogenic-arthritis-pyoderma-gangrenosum-and-acne

ORDO:69126
OMIM:604416

caused by heterozygous mutation in the PSTPIP1 gene (606347) on chromosome 15q24.


https://www.ncbi.nlm.nih.gov/pubmed/28251506
https://www.ncbi.nlm.nih.gov/pubmed/28236224

**Comment by Antonialock** [comment]
Hi Lynn, I can't see this term in DO, what's the ID? Cheers
