### ISSUE TITLE
OMIM:266265 is on three different DOIDs:

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#648]
id: DOID:0070255
name: congenital disorder of glycosylation type IIc
def: "A congenital disorder of glycosylation type II that has_material_basis_in an autosomal recessive mutation of SLC35C1 on chromosome 11p11.2."

id: DOID:6612
name: leukocyte adhesion deficiency
def: [no DEF]

id: DOID:0050571
name: congenital disorder of glycosylation type II
def: "A congenital disorder of glycosylation that involves malfunctioning trimming/processing of the protein-bound oligosaccharide chain."

I think the xref should reamain on DOID:0070255 and be removed from DOID:0050571.  Not sure about DOID:6612 - maybe merge with DOID:0070255??

**Comment by lschriml** [comment]
Thank you Steven,
  the subtype OMIM IDs have been removed from congenital disorder of glycosylation type II. 
And the other terms have been reviewed and updated. 

This one is complicated :) 


**congenital disorders of glycosylation, type II.**  DOID:0050571
OMIM:266265
synonym: LEUKOCYTE ADHESION DEFICIENCY, TYPE II; LAD2
congenital disorder of glycosylation type IIc (CDG2C) is caused by homozygous or compound heterozygous mutation in the SLC35C1 gene (605881), which encodes a GDP-fucose transporter, on chromosome 11p11.

--> I am removing the LAD2 synonym from **congenital disorders of glycosylation, type II**, DOID:0050571
--> OMIM:266265 --> will stay associated with congenital disorders of glycosylation, type II


**The NORD page outlines the three types of LAD**
https://rarediseases.org/rare-diseases/leukocyte-adhesion-deficiency-syndromes/

LAD:
All affected individuals develop an increased susceptibility to developing recurrent bacterial and fungal infections
LAD syndromes are characterized by defects affecting how white blood cells (leukocytes) respond and travel to the site of a wound or infection
affecting the immune system

---> I will create a LAD2 DO term,
     and will add the xref for Orphanet 
ORPHA:99843  Leukocyte adhesion deficiency type II
Leukocyte adhesion deficiency type II (LAD-II) is a form of LAD (see this term) characterized by recurrent bacterial infections, severe growth delay and severe intellectual deficit.




In OMIM: 
The neutrophil defect in CDG2C has been referred to as 'leukocyte adhesion deficiency type II' (LAD2), which is a manifestation of the disorder; there are no cases of 'primary' LAD II

--> In congenital disorders of glycosylation, type II, therefore, LADII is a co-morbidity, but not the same disease. 



**Leukocyte Adhesion Deficiency Syndromes**
https://rarediseases.org/rare-diseases/leukocyte-adhesion-deficiency-syndromes/
Leukocyte adhesions deficiency (LAD) syndromes are a group of rare disorders affecting the immune system. LAD syndromes are characterized by defects affecting how white blood cells (leukocytes) respond and travel to the site of a wound or infection. 

LAD II may also be known as congenital disorder of glycosylation type IIc due to the primary defect in fucose metabolism.

    

**leukocyte adhesion deficiency**.    DOID:6612
Leukocyte adhesions deficiency (LAD) syndromes are a group of rare disorders affecting the immune system. LAD syndromes are characterized by defects affecting how white blood cells (leukocytes) respond and travel to the site of a wound or infection. Three distinct types of leukocyte adhesion syndrome have been identified

Orphanet:
Leukocyte adhesion deficiency (LAD) is a primary immunodeficiency characterized by defects in the leukocyte adhesion process, marked leukocytosis and recurrent infections.


**leukocyte adhesion deficiency 1**     DOID:0110910.   autosomal recessive
A leukocyte adhesion deficiency that has_material_basis_in mutation of the ITGB2 gene on chromosome 21q22.3. 
OMIM:116920
     Leukocyte adhesion deficiency (LAD) is an autosomal recessive disorder of neutrophil function resulting from a deficiency of the beta-2 integrin subunit of the leukocyte cell adhesion molecule. 

**leukocyte adhesion deficiency 3**.   DOID:0110912.   - autosomal recessive
A leukocyte adhesion deficiency that has_material_basis_in mutation of the KIND3 gene on chromosome 11q13.1. 

--> I have updated the definition for LAD3

Gene nomenclature: current gene name: FERMT3 , previous name: KIND3

OMIM:612840
A number sign (#) is used with this entry because LAD3 can be caused by homozygous mutation in the FERMT3 gene (607901) on chromosome 11q12.

Orphanet: 
**Leukocyte adhesion deficiency type III** (LAD-III) is a form of LAD (see this term) characterized by both severe bacterial infections and a severe bleeding disorder.


Cheers,
Lynn

**Comment by sjm41** [comment]
Great, thanks for doing all this research and sorting it out.

I think the following bit was meant to refer to "congenital disorder of glycosylation type **IIc**" (DOID:0070255), right?

==
**congenital disorders of glycosylation, type II.** DOID:0050571
OMIM:266265
synonym: LEUKOCYTE ADHESION DEFICIENCY, TYPE II; LAD2
congenital disorder of glycosylation type IIc (CDG2C) is caused by homozygous or compound heterozygous mutation in the SLC35C1 gene (605881), which encodes a GDP-fucose transporter, on chromosome 11p11.

--> I am removing the LAD2 synonym from **congenital disorders of glycosylation, type II**, DOID:0050571
--> OMIM:266265 --> will stay associated with congenital disorders of glycosylation, type II
==

**Comment by lschriml** [comment]
thank you for catching my typo in these notes:
I removed the synonym from the parent term, and have associated the OMIM ID with the child term, # IIc 

--> OMIM:266265 --> will stay associated with congenital disorders of glycosylation, type IIc 
 this is: DOID:0070255

Cheers,
Lynn
