### ISSUE TITLE
'located in'

### ISSUE THREAD

**Issue by aellenhicks** [DiseaseOntology/HumanDiseaseOntology#649]
I am creating a domain ontology for hypertension and have found that when I add domain and range restrictions to RO_0001025 'located in' the DO classes using RO_0001025 'located in' in the class restrictions are unsatsifiable. 

The reason for this is that 'located in' is defined as 'a relation between two independent continuants, the target and the location, in which the target is entirely within the location', so I have added 'independent continuant' in the domain restriction. However, classes such as 'vascular disease' use the 'located in' relation, entailing that a vascular disease is an independent continuant.

**Comment by lschriml** [comment]
Hello,
  thank you for letting us know about this issue you are having. 
I'm not sure how to approach a resolution for you. 
Do you have suggestions ? 
Cheers,
Lynn

**Comment by sbello** [comment]
Hi Lynn,
Possibly we should be using 'inheres in' or 'inheres in part of' rather than 'located in' to relate disease to anatomy? Looking at RO 'inheres in' relates "a specifically dependent continuant (the dependent) and an independent continuant (the bearer), in which the dependent specifically depends on the bearer for its existence". I believe disease or disorder is a subtype of specifically dependent continuant. We mostly us inheres in and inheres in part of in the MP logical definitions..
Sue

**Comment by cmungall** [comment]
Note that you won't be able to use the inheres-in part-of chain if you want to state a single disease has multiple spatially disjoint locations. I'm not sure if that causes a problem

You could use the weaker http://purl.obolibrary.org/obo/RO_0004026 relation

**Comment by sbello** [comment]
Good point Chris. That would be a problem. The relation you suggest 'disease has location' looks like the best option.

**Comment by aellenhicks** [comment]
I also think this is a good option also. Thank you!
