### ISSUE TITLE
NTR: hereditary diffuse leukoencephalopathy with axonal spheroids

### ISSUE THREAD

**Issue by sabrinatoro** [DiseaseOntology/HumanDiseaseOntology#696]
NTR : 
hereditary diffuse leukoencephalopathy with axonal spheroids

Synonyms : 
HDLS
adult-onset leukoencephalopathy with axonal spheroids and pigmented glia 
ALSP

parent term: 
leukodystrophy (DOID:10579)

Xref: 
OMIM: 221820

**Comment by lschriml** [comment]
Thank you for this new term !! 

I've created a new DO term: 
DOID:0080523
adult-onset leukoencephalopathy with axonal spheroids and pigmented glia


OMIM:221820
 hereditary diffuse leukoencephalopathy with spheroids 

is caused by heterozygous mutation in the CSF1R gene (164770) on chromosome 5q32.
is an autosomal dominant adult-onset rapidly progressive neurodegenerative disorder characterized by variable behavioral, cognitive, and motor changes. 

GHR: **adult-onset leukoencephalopathy with axonal spheroids and pigmented glia**
  def: 
  characterized by changes to certain areas of the brain. A hallmark of ALSP is leukoencephalopathy, which is the alteration of a type of brain tissue called white matter.

ORPHA:313808
Hereditary diffuse leukoencephalopathy with axonal spheroids and pigmented glia 
  is a rare autosomal dominant disease characterized by a complex phenotype including progressive dementia, apraxia, apathy, impaired balance, parkinsonism, spasticity and epilepsy.


UMLS: C3711381
GARD:10981

https://www.ncbi.nlm.nih.gov/pubmed/28921817
https://www.ncbi.nlm.nih.gov/pubmed/27680516

Cheers,
Lynn
