### ISSUE TITLE
new term request from Xenbase: channelopathy

### ISSUE THREAD

**Issue by Xenbase2** [DiseaseOntology/HumanDiseaseOntology#723]
New term request: channelopathy

Suggested definition: A disease or syndrome, either congenital or acquired, caused by the disturbed function of ion channel subunits or the proteins that regulate them

Ref:https://en.wikipedia.org/wiki/Channelopathy

See Wikipedia entry for list of diseases/syndromes that should be children of channelopathy.

**Comment by lschriml** [comment]
This term represents a large category of diseases resulting from the dysfunction of ion channels, as such, I do not think it should be added to the DO as a type of disease. 

Rather: 
   --> This could be annotated with GO:0008200, ion channel inhibitor activity
As this is such a broad category, I would suggest one solution would be to create a logical definition
for the ion channel mutation. dysfunction.

In DO, we have not yet brought in an import of the GO. 

Cheers,
Lynn 

Reference: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3935107/

Channelopathies are a heterogeneous group of disorders resulting from the dysfunction of ion channels located in the membranes of all cells and many cellular organelles. These include diseases of the nervous system (e.g., generalized epilepsy with febrile seizures plus, familial hemiplegic migraine, episodic ataxia, and hyperkalemic and hypokalemic periodic paralysis), the cardiovascular system (e.g., long QT syndrome, short QT syndrome, Brugada syndrome, and catecholaminergic polymorphic ventricular tachycardia), the respiratory system (e.g., cystic fibrosis), the endocrine system (e.g., neonatal diabetes mellitus, familial hyperinsulinemic hypoglycemia, thyrotoxic hypokalemic periodic paralysis, and familial hyperaldosteronism), the urinary system (e.g., Bartter syndrome, nephrogenic diabetes insipidus, autosomal-dominant polycystic kidney disease, and hypomagnesemia with secondary hypocalcemia), and the immune system (e.g., myasthenia gravis, neuromyelitis optica, Isaac syndrome, and anti-NMDA [N-methyl-D-aspartate] receptor encephalitis).

Channelopathies are diseases that develop because of defects in ion channels caused by either genetic or acquired factors (Fig. 1). Mutations in genes encoding ion channels, which impair channel function, are the most common cause of channelopathies. 

Consistent with the distribution of ion channels throughout the human body, ion channel defects have been implicated in a wide variety of diseases, including epilepsy, migraine, blindness, deafness, diabetes, hypertension, cardiac arrhythmia, asthma, irritable bowel syndrome, and cancer1-3).
