### ISSUE TITLE
review inheritance patterns for some genetic diseases

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#733]
Steven Marygold reported this in the Alliance email list:
Previously (I’m looking at the DO file dated 2019-03-01), "genetic disease" had just two children:
"chromosomal disease”
"monogenic disease"
And, for that reason, we chose to use those two terms in our ribbon slim.

But now (looking at the DO file dated 2019-07-15), “genetic disease" has 754 children, as many other specific diseases now have it as a direct parent term. (screen shot attached)

Steven

![Screen Shot 2019-07-31 at 09 57 39](https://user-images.githubusercontent.com/10979793/62216181-46fcdb80-b376-11e9-8a55-63c8bc52fe2c.png)

If you look at the example 3-Methylcrotonyl-CoA carboxylase deficiency (DOID:0050710) I think the direct placement under genetic disease is correct as this lists 2 potential genes. But the example 3-methylglutaconic aciduria type 1 (DOID:0110002) looks like it should live under monogenic disease.

Not sure if this is an axiom issue or a build process issue.

Thanks, 
Sue

**Comment by sbello** [comment]
Also from Steven:
I note that some classes like 'inherited metabolic disorder' have a single parent 'disease of metabolism', and do not subclass 'genetic disease', which seems like an omission, ..

**Comment by cmungall** [comment]
It looks like most of these follow the same pattern:

![image](https://user-images.githubusercontent.com/50745/62218147-e1125300-b379-11e9-91ac-22fbfb97aee4.png)

Aside: is structural_variant the correct SO class to use here?

I think it would be good if we in the Alliance explicitly stated some requirements inherent in our ribbon, e.g. that genetic disease should have no leaf nodes asserted under it (for example), then the DO folks could encode this as sparql constraints in robot - or give counter-examples, which we can then take into account for the ribbon

**Comment by lschriml** [comment]
Thank you Steven for pointing this out.
Apologies, I did not catch this formatting change in our release files.
I am adding Becky to the ticket, as she will help us figure out the fix.

Looking at the latest release folder, doid.owl file,
 I see the same thing you do.
This is not an intentional change. 

In our working file, diid-edit.owl, the tree is appearing as expected;



--> the is not the data, rather the formatting of the release file.

We will look into this right away and get it fixed.
<img width="533" alt="Screen Shot 2019-07-31 at 9 59 16 AM" src="https://user-images.githubusercontent.com/4333069/62218530-a3fa9080-b37a-11e9-8cd4-d83d852fe0fa.png">

Cheers,
Lynn

**Comment by lschriml** [comment]
Becky and I looked into this:
   Updating my previous note, the release files are fine. No errors.
 Listing all diseases that have a genetic basis as inferred child terms of genetic disease is what 
we intended to do. 

If you are looking at the doid.obo or doid.owl files, they are post reasoned.
We implemented the Axiom: disease and ('disease has basis in' some structural_variant) this past year to enable classification of disease that have a genetic basis as inferred child terms of genetic disease. 
    
We chose the SO's 'structural variant' to define genetic diseases:

<img width="544" alt="Screen Shot 2019-07-31 at 11 07 35 AM" src="https://user-images.githubusercontent.com/4333069/62223768-7ebe5000-b383-11e9-9202-808002616126.png">

As we are defining genetic diseases in the DO based on their 'sequence variant' >> 'structural variant' 

   We have had some mysterious disappearances of EQ and SubClass axioms since last fall (documented in the DO Github and with Protege). 

In the Spring this year, we did an update to bring back the 'genetic disease' EQ statement. 
And had to re-introduce many anatomy and cell type axioms. 

That is the major change that was reported by Steven. 
The inherited terms mentioned in this ticket since that time have lost their statements. 
I have now added them back. 

We will do another review to see what else has been lost. 

Thank you everyone, for contributing to the resolution of this issue. 

Cheers,
Lynn

**Comment by lschriml** [comment]
We would appreciate any help in figuring out these bugs. 
@jbmunro has been leading this effort. 
Lynn

**Comment by lschriml** [comment]
I am reviewing the disease terms with the inferred parent 'genetic disease'.

This involves further refining this branch: 
     genetic disease
         monogenic disease
         polygenic disease
               digenic disease

adding these two categories, will now allow us to further classify DO's genetic diseases.
For: 
 3-Methylcrotonyl-CoA carboxylase deficiency
     --> this is an 'autosomal recessive disease', I have added it's two subtypes, based on OMIM.

Cheers,
Lynn

**Comment by cmungall** [comment]
Let's find @mikebada here at ICBO and ask about structural variant, I would have thought structural variants not to encompass single nucleotide changes, but the SO def seems overly broad?

**Comment by lschriml** [comment]
These have all been fixed. 
Updated in GitHub.

Cheers,
Lynn

**Comment by sjm41** [comment]
Hi Lynn,

Can I just confirm the final resolution/plan here?

_**Listing all diseases that have a genetic basis as inferred child terms of genetic disease is what
we intended to do.**_

_**I am reviewing the disease terms with the inferred parent 'genetic disease'.
This involves further refining this branch:
genetic disease
monogenic disease
polygenic disease
digenic disease**_
Does this mean you'll be adding 'polygenic disease' and 'digenic disease' as direct children of 'genetic disease', and then the new inferred genetic diseases will go under one of these child terms?
Or will some/a lot of these inferences still get put directly under the parent 'genetic disease', where a more specific association cannot be made?  (I'm seeing >750 direct child terms of 'genetic disease' in the obo file, but I realise that isn't the most up-to-date.)

Just trying to figure out how many direct children there will be under 'genetic disease' in the final reckoning.

Thanks.

**Comment by lschriml** [comment]
Hello Steven,
    I did add polygenic & digenic disease, reviewed all terms. 
Most of the terms that had been under 'genetic disease' could be more specifically classified under monogenic >> autosomal recessive/dominant disease. 

I've posted here a screen shot to show the final resolution.
I'll make these public in a release next week.

Cheers,
Lynn
<img width="433" alt="Screen Shot 2019-08-02 at 9 07 26 AM" src="https://user-images.githubusercontent.com/4333069/62372336-37f86380-b505-11e9-9ee0-3c93d89e15ec.png">

**Comment by sjm41** [comment]
OK, thanks for the clarification Lynn.
Steven.
