### ISSUE TITLE
glomuvenous malformations (OMIM:138000)

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#751]
I'm working on the OMIM term glomuvenous malformations (OMIM:138000|ORDO:83454). The Orphanet record has both multiple glomangiomas and glomangiomatosis as synonyms. DO has separate entries for glomangioma (DOID:2436) and glomangiomatosis (DOID:6906). The first lacks a definition the second has only a minimal definition. It is unclear to me that these are not the same thing. Even looking at the NCIT entries it is not clear to me that these are distinct disorders. The OMIM record is specific for ones caused by mutation in GLML.

I could use a second opinion on if these are distinct entities and if so where should the entity in the OMIM record and the Orphanet record be placed?

**Comment by lschriml** [comment]
glomuvenous malformations (OMIM:138000|ORDO:83454)

glomangioma (DOID:2436)

glomangiomatosis (DOID:6906)
    A benign perivascular tumor that is characterized as a vascular variant of a glomus tumor.
PubMed:28656356,  Glomangiomatosis is a benign vascular variant of a glomus tumor.
additional citations: 
PMID: 12376927 PMID: 28303299

**University of Washington, Pathology Outlines** 
http://www.pathologyoutlines.com/topic/softtissueglomus.html

**Glomus tumor**
Revised: 5 November 2019
Cite this page: Obeidin F, Alexiev B. Glomus tumor. PathologyOutlines.com website. http://www.pathologyoutlines.com/topic/softtissueglomus.html. Accessed February 4th, 2020.

--> Definition: Mesenchymal tumor composed of modified smooth muscle cells arising from the glomus body

Note: Usually benign with very rare malignant variants

**Terminology**
Name differs based on morphology: glomus tumor, glomangioma, glomangiomyoma and glomangiomatosis

**Microscopic (histologic) description**
Well circumscribed mass composed of 3 components: glomus cells, vasculature and smooth muscle cells
Solid glomus tumor (75% of cases): predominantly glomus cells, poor vasculature and rare smooth muscle cells
**Glomangioma** (20% of cases): tumors with prominent vascular component

Rare variants have microscopically infiltrative and diffuse growth and are known as **glomangiomatosis**

**Pathophysiology**
Familial glomus tumors (**glomuvenous malformations**) are caused by inactivating mutations in the glomulin gene expressed in vascular smooth muscle cells (Am J Hum Genet 2013;92:188)

==========================================================
**To Do:** 
[cancer branch]
Hemangiopericytic Neoplasm -- obsolete, NCI : Obsolete Concept 
perivascular tumor
        - remove NCI: C6528 - the ID is for malignant OR benign
glomus tumor - mv to be child of perivascular tumor
                         - rename: malignant glomus tumor

 **[benign neoplasm branch]**
add benign glomus tumor, as child of benign perivascular tumor
   - child terms: **glomangiomatosis**
                           **glomangioma** - using NCI definition: 
A morphologic variant of the glomus tumor characterized by the presence of dilated veins, surrounded by small clusters of glomus cells. Glomangiomas are most often present in patients with multiple lesions.
         
--> Add child term: 
**Familial glomus tumors** (**glomuvenous malformations**)
              glomuvenous malformations (OMIM:138000|ORDO:83454)
 exact synonym:  **hereditary paraganglioma**
            http://atlasgeneticsoncology.org/Kprones/HeredParagangID10043.html
     defn:  In the familial forms, they are preferentially localized in the head and neck, in the carotid 
                body (80%) and in the glomus jugulare (20%). 

Neoplastic Risk: Tumors are usually benign. 

--> Looks to me that the name to use for this term would be: 
hereditary paraganglioma --> is most widely used in PubMed
glomuvenous malformation --> is used, but only about 1/3 as much as hereditary paraganglioma

Cheers,
Lynn
