### ISSUE TITLE
missing parentage infantile cerebellar-retinal degeneration (DOID:0050883)

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#757]
infantile cerebellar-retinal degeneration (DOID:0050883)
is missing:
is_a (or has_part?) optic atrophy (DOID:5723)

**Comment by melodyswen** [comment]
Hi!

Thanks very much for your comment - we appreciate the feedback! 

I'm in favor of keeping infantile cerebellar-retinal degeneration as a child of neurodegenerative disease, as that is its primary path as a disease is cerebellar degeneration. Optic atrophy characterizes the disease. 

We could add a logical definition for a vision symptom. 

Cheers,
Melody

**Comment by Antonialock** [comment]
is multiple parent terms not allowed? Does/could it also have
is_a autosomal recessive disease
?

**Comment by Antonialock** [comment]
(aco2 causative mutation https://www.omim.org/entry/614559)

**Comment by ValWood** [comment]
Hi Melody,

Are you saying that  optic atrophy (DOID:5723) is a 'characteristic of the disease' rather than a 'type of disease' and that you classify these differently? If so how do you draw the distinction? This may help us to recognise when a parent is appropriate.

Also, if this is the case, what relationship(s) do you use to link disease characteristics to diseases?

We would like to  figure out which of our tickets are outstanding for this reason. We are wating for quite a few additional parents to improve our PomBase disease slim with a hope to announce it to the community in the next few weeks.

It would be useful to know if there is a good reason why these should not be added as then we can look to revise our  use of such terms accordingly. As far as I know, all of the disease terms we use are to describe specific diseases, but Antonia should be able to confirm this.

**Comment by ValWood** [comment]
I just checked and this appears to be a standard 'disease classification' .

So could you explain again why the parent can't be added? It isn't clear to me either.

Thanks
Val

**Comment by melodyswen** [comment]
Hi everybody, 

Thank you for your thoughtful responses. We discussed this issue as a team, and I have added an inferred parent as 'autosomal recessive' to this DOID term to the OWL file. We have primary parents and inferred parents for the Disease Ontology. For now, the primary parent is still neurodegenerative disease. 

Val, what do you mean by standard 'disease classification'? Are you saying that optic atrophy is a standard disease classification for infantile cerebllar  retinal degeneration? 

I agree that it can be difficult to discern the line between 'characteristic of the disease' rather than a 'type of disease'. Ultimately, I think of the initial mechanism that leads to the disease. We've recently imported a series of optic atrophy related diseases from OMIM, and are also thinking about how to best classify them under a parent. 

To try to address your question of how to link disease characteristics to disease, we have a Symptom Ontology within our Disease Ontology that we use to connect symptoms/characteristics. 

Please let me know if you have any other questions - we're always open to discussion and collaboration!

Cheers,
Melody

**Comment by ValWood** [comment]
I  forgot what I was looking at, but I think what I meant was that optic atrophy was described as a disease in OMIN
https://www.omim.org/entry/165500

I think I now see what you mean: "Optic atrophy is not a disease, but rather a sign of a potentially more serious condition." https://my.clevelandclinic.org/health/diseases/12326-optic-atrophy

However, here you classify it as a disease
http://www.disease-ontology.org/?id=DOID:5723
(I guess to cover the juvenile onset where the primary disorder does appear to be optic atrophy?)

So  you would not classify infantile cerebellar-retinal degeneration  as  a optic atrophy because it is one of a collection of symptoms? 

Is there any documentation  you describe how you classify a disease primary pathology  in DO?  It seems that in many cases this could be quite arbitrary  but I presume you must have some rules. 


Also, do you connect diseases to symptoms in the ontology with any other relationship (has_part) for example?  We are trying to establish if we can use DO consistently 
to retrieve genes of interest using particular classifiers.
 
If we have this information  we can probably revise some of  our outstanding requests.

**Comment by ValWood** [comment]
Another question, how do you define a "primary parent" and an "inferred parent"? I haven't come across  this type of parentage before, do you use different relationships for these?

**Comment by sbello** [comment]
Hi Val,
The 'primary parent' is the one asserted using the 'is a' relationship in the edit file. The inferred parents are derived from other relationship types for example 'has material basis in' is used to create relationships between diseases and the type of inheritance of the disease.

The build process will create 'is a' relationships based off of these other relationships using a reasoner. In the files that contain (doid.obo, doid.owl, doid-merged.obo, doid-merged.owl) these 'is a' parents based off these other relationships you won't notice a difference between the asserted and inferred parents. But this allows us to construct the single is hierarchy files as well.

GO uses a similar approach in building their ontologies as you don't have to worry so much about asserting all the correct parents, you can rely on the relationships and the reasoner to create the full set of parents.

Sue

**Comment by cmungall** [comment]
Hope this helps, but I just wanted to clarify one thing. GO does not really have the concept of primary parent. A lot of compositional terms fall into nice patterns where there is a single asserted 'genus', and we gets of nice inference of parents (often the genus is "deepened"), and we don't have to do any additional assertion. In general we try and avoid editors asserting things that could be inferred, because in our experience this leads to a more maintainable ontology.

However the overriding principle is to give the curators and the community what they want, and sometimes that means asserting multiple is-a parents. It tends to happen less in GO because part-of is so prominent. But we still strive to produce the most complete end product we can, which can involve asserting multiple is-as.

I know I have attempted before to provide guidance on this topic here and not always successfully, but as GO was brought up I felt the need to clarify. Hope this helps.

**Comment by sbello** [comment]
Thanks Chris.

**Comment by ValWood** [comment]
OK thanks for the info. I understand.
