### ISSUE TITLE
upodate description DOID:0090049

### ISSUE THREAD

**Issue by Antonialock** [DiseaseOntology/HumanDiseaseOntology#758]
DOID:0090049 descr says
"has_material_basis_in autosomal dominant inheritance of heterozygous mutation in the myofibrillogenesis regulator-1 (MR1) gene o"

but the hgnc approved symbol for this gene is PNKD

**Comment by melodyswen** [comment]
Hi! 

Thanks for this comment. 

On the OMIM entry for the cross-referenced OMIM term, #118800, it states:
"A number sign (#) is used with this entry because of evidence that paroxysmal nonkinesigenic dyskinesia-1 (PNKD1) is caused by heterozygous mutation in the myofibrillogenesis regulator-1 gene (MR1; 609023) on chromosome 2q35."

Our description may need to be updated - we'll review and get back to you!

Cheers,
Melody

**Comment by lschriml** [comment]
Agreed, 
The gene name has changed:
https://ghr.nlm.nih.gov/condition/familial-paroxysmal-nonkinesigenic-dyskinesia#genes

We will update our definition to: 

A dystonia that is characterized by attacks of dystonic or choreathetotic movements precipitated by stress, fatigue, coffee or alcohol intake or menstruation, and has_material_basis_in autosomal dominant inheritance of heterozygous mutation in the PNKD metallo-beta-lactamase domain containing gene on chromosome 2q35. 


Cheers,
Lynn

**Comment by melodyswen** [comment]
Hi @Antonialock , the definition has been updated according to Lynn's description above. The change will be reflected in our next release. 

Cheers,
Melody
