### ISSUE TITLE
early onset and late onset Alzheimers

### ISSUE THREAD

**Issue by melodyswen** [DiseaseOntology/HumanDiseaseOntology#765]
Alzheimers 1 2 3 4 5 is the OMIM source. But users are more familiar with early onset and late onset. How can early onset and late onset be more integrated?

**Comment by lschriml** [comment]
@sbello -- How do you feel about categorizing based on early or late onset. 

Question: what do we do with subtypes that are not defined as either early or late, or where the age range does not align with either early or late ? 
 

EARLY-ONSET
Alzheimer's disease 1     
Alzheimer's disease 3 
Alzheimer's disease 4
Alzheimer's disease 10

People who have a clinical onset of Alzheimer’s disease (AD) before the age of 65 years are diagnosed with early-onset Alzheimer’s disease (EOAD).



 LATE-ONSET
Alzheimer's disease 2
Alzheimer's disease 5
Alzheimer's disease 6
Alzheimer's disease 8
Alzheimer's disease 9
Alzheimer's disease 11
Alzheimer's disease 13
Alzheimer's disease 14
Alzheimer's disease 15
Alzheimer's disease 16
Alzheimer's disease 17     
Alzheimer's disease 18  
Alzheimer's disease 19


Alzheimer's disease 12
Age at disease onset ranged from 53 to 78 years, but in 10 of the families there was at least 1 member with age at onset of less than 65 years. 

 Alzheimer's disease 7
    -- no onset info in OMIM

**Comment by sbello** [comment]
I wonder if we should just create the 'early onset' class to group those with an unusually early onset since typically Alzheimer's is a late-onset disease. Trying to define how late-onset Alzheimer's differs from 'regular' onset strikes me a a difficult needle to thread. Unless we define late in a way that covers everything that isn't early. This strikes me as the same issue we had with Parkinson's that we discussed with Ada where the early/late tag is often based on the first couple of patients and doesn't necessarily  reflect the typical age of onset.

If we do go down this path, I think we'll also need to have some fuzziness in the definition since even the early onset versions may have later onset patients. Maybe something like "An Alzheimer disease characterized by onset of symptoms before the age of 65 in many patients."

We could leave those with no age of onset information or age of onset that spans the early/late split without a majority of cases on one side or the other as direct children of Alzheimer's disease.

I'll continue to think about this.

**Comment by lschriml** [comment]
Good points Sue.

I was thinking about this last night.
How about we just add a synonym following OMIM,
  add exact synonym : 
late-onset Alzheimer’s disease 15

It is a simple solution, without having to create new category terms.

What do you think ?

Lynn

**Comment by sbello** [comment]
I like the synonym plan. I can work on that this afternoon.

**Comment by lschriml** [comment]
Sounds good !!

**Comment by melodyswen** [comment]
This sounds good to me - I know some users will appreciate the new synonyms. Thanks!

**Comment by lschriml** [comment]
UniProt group has asked for re-review;

My notes: 
he DO team (cc'd) has been exploring how to best represent Alzheimer's. 

   Thus far, we have been including the OMIM term names, as synonyms, to 
   inform early or late onset. 

   From GeneReviews, with proposed restructuring of DO: 

  What do you think ?



   Alzheimer's disease

        nonfamilial Alzheimer's disease. [new term to add in DO]
                -  an individual with AD and no known family history of AD (75% is nonfamilial )
                        (aka: non-familial AD)

        familial Alzheimer's disease [new term to add in DO]
                      -  ≥3 persons in a family have AD (Approximately 25% of all AD is familial)

            early-onset Alzheimer's disease [new term to add in DO]
                        (aka: Early-onset familial AD (EOFAD)
                         - occurs in multiple members of a family with a mean onset usually before age 65 years
                              (GeneReviews:  APP, PSEN1, PSEN2)
                                         (OMIM:AD1, AD3, AD4, AD10)
                          early-onset autosomal dominant:     
                                                                   [Note: all early-onset Alzheimer's diseases are autosomal dominant, this term is synonymous to  early-onset Alzheimer's disease]
                                   AD1, AD3, AD4, AD10
           
            late-onset Alzheimer's disease  [new term to add in DO]
                       (aka: late-onset familial AD) (age >60-65 years) 
                                GeneReviews: 
 - APOE e4 allele variants
                                  (OMIM: AD2, AD5, AD6, AD8, AD9, AD11, AD13-19)
                                  late-onset autosomal dominant:
                                  AD2, AD5, AD9

                                  AD6, AD8, AD11, AD13-19  - late-onset, inheritance ??

       AD7 - not know early or late
      AD 12 - disease onset ranged from 53 to 78 years


  Question:  
   What are the groups thoughts on handling Alzheimer's subtypes
     where age of onset includes both early and late ?

**Comment by sbello** [comment]
I kept thinking we had discussed this with OMIM but I think that is because we discussed early/late Parkinson's with them (see ticket #702) There we used the mean age of onset to decide if a type should be early or late. I would suggest using mean age for Alzheimer's as well. We could leave those with no age or no clear mean age sitting under the parent familial term.

**Comment by sbello** [comment]
While we're looking at this, need to consider what to do with OMIM:502500 https://www.omim.org/entry/502500?search=502500 
ALZHEIMER DISEASE, SUSCEPTIBILITY TO, MITOCHONDRIAL

**Comment by lschriml** [comment]
@sbello - let's revisit this ticket. 
Lynn

**Comment by lschriml** [comment]
> While we're looking at this, need to consider what to do with OMIM:502500 https://www.omim.org/entry/502500?search=502500
> ALZHEIMER DISEASE, SUSCEPTIBILITY TO, MITOCHONDRIAL

@sbello - I think we can add this to the susceptibility import.
Cheers,
Lynn

**Comment by lschriml** [comment]
No work needed for this ticket. Closing.
