### ISSUE TITLE
New term request for OMIM 618456 (DFNB114)

### ISSUE THREAD

**Issue by sjm41** [DiseaseOntology/HumanDiseaseOntology#797]
Can you create an entry for:
DEAFNESS, AUTOSOMAL RECESSIVE 114; DFNB114
https://www.omim.org/entry/618456

Will be child of:
DOID:0050565 autosomal recessive nonsyndromic deafness

Need it to accurately curate disease model in PMID: 30610177

Thanks.

**Comment by tutajm** [comment]
And it will be really great if you consider adding similar related new terms as well: 

DFNB57  OMIM:618003
DFNB94  OMIM:618434
DFNB99  OMIM:618481
DFNB100 OMIM:618422
DFNB109 OMIM:618013
DFNB110 OMIM:618094
DFNB111 OMIM:618145
DFNB112 OMIM:618257
DFNB113 OMIM:618410
DFNB114 OMIM:618456 (requested in the ticket)
DFNB115 OMIM:618457

Benefit: by adding these, you will have a complete set of OMIM-based terms in 'autosomal recessive nonsyndromic deafness' parent term!

Thank you,
Marek

**Comment by sbello** [comment]
Will do Marek, thanks for identifying these. It is my practice to check the full OMIM series whenever adding a member of the series to identify and add any other members that were created since the last review.
Best regards,
Sue

**Comment by sbello** [comment]
added to the MGI ROBOT spreadsheet

**Comment by sjm41** [comment]
One other question:
The authors of PMID: 30610177 use the terms "sensorineural hearing loss" ( = DOID:10003) and "autosomal recessive nonsyndromic deafness" (= DOID:0050565) to refer to the described deafness.
But those two DO terms appear to be unrelated in the DO.  Should they have some kind of relationship?

**Comment by sbello** [comment]
I think this has more to do with the line between phenotype and disease. The term ""sensorineural hearing loss" is also found in the MP (MP:0004740) and HPO (HP:0000407) as a phenotype since it describes a type of hearing loss. Not all "autosomal recessive nonsyndromic deafness" may necessarily be due to sensorineural hearing loss.
@melodyswen @lschriml  this might be another example to bring up during the workshop at Biocuration in May
