### ISSUE TITLE
NTR OMIM:600329 OSTEOPETROSIS AND INFANTILE NEUROAXONAL DYSTROPHY 

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#820]
OSTEOPETROSIS AND INFANTILE NEUROAXONAL DYSTROPHY   https://omim.org/entry/600329
and a new paper
 http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=search&db=PubMed&dopt=Abstract&term=30982608

**Comment by lschriml** [comment]
Reviewing this term: 

Reading new paper (below),
  I would create a new DO term: 
        CSF1R-related brain malformation and osteopetrosis 
            synonym: osteoporosis and infantile neuroaxonal dystrophy
            OMIM: 600329

as a child of : neuroaxonal dystrophy DOID:2367
        
       xrefs: 10082

https://pubmed.ncbi.nlm.nih.gov/30982608

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6506793/

There are at least two previous reports of individuals with similar features. In 1995, Rees et al. described two siblings with “infantile neuroaxonal dystrophy and osteopetrosis,” and, with great foresight, noted similarity to the spontaneously arising osteopetrosis mouse, now known to be due to mutations in colony stimulating factor 1 (CSF1), the CSF1R ligand.34 More recently, Monies et al. described two siblings with brain malformations and osteopetrosis, whose parents both carried the same heterozygous truncating CSF1R mutation, but DNA was unavailable from the siblings to confirm that they were both homozygous and no pathologic data was available.33 We summarized key phenotypic features of individuals with confirmed homozygous mutations (individual II-1 from family CSF1R_01 and individual II-4 from family CSF1R_02), likely homozygous mutations (Monies et al.33 sibs 1 and 2), and unsequenced individuals (Rees et al.34 sibs 1 and 2) in Table 1. Although the size of this cohort is insufficient to know the full **phenotypic spectrum,** 
     agenesis of corpus callosum, periventricular calcifications, ventriculomegaly, osteopetrosis, and hypocalcemia were seen in the majority, and axonal spheroids were seen in all individuals who underwent neuropathological examination.

reference 33:
33. Monies D., Maddirevula S., Kurdi W., Alanazy M.H., Alkhalidi H., Al-Owain M., Sulaiman R.A., Faqeih E., Goljan E., Ibrahim N. Autozygosity reveals recessive mutations and novel mechanisms in dominant genes: implications in variant interpretation. Genet. Med. 2017;19:1144–1150. [PubMed] [Google Scholar]

**Comment by melodyswen** [comment]
New term has been added
