### ISSUE TITLE
NTR  citrullinemia child terms

### ISSUE THREAD

**Issue by tutajm** [DiseaseOntology/HumanDiseaseOntology#822]
Please create child terms for DOID:9273 'citrullinemia', for OMIM:215700, OMIM:603471, OMIM:605814.

Needed for curation. Thank you!

**Comment by lschriml** [comment]
To Do:
   add two child terms to citrullinemia, update definition, add definition xref, add synonym: classic citrullinemia
    move OMIM xrefs to appropriate child terms.
     (1)      neonatal-onset type II citrullinemia. (add synonym neonatal-onset type 2 citrullinemia)
--> add 'autosomal recessive inheritance axiom' 
    (2) adult-onset type II citrullinemia, add synonym: ,  citrin deficiency

Review: 
**citrullinemia**
    https://en.wikipedia.org/wiki/Citrullinemia
          [DO]:  An urea cycle disorder that involves the accumulation of ammonia in the blood. 

     source: https://ghr.nlm.nih.gov/condition/citrullinemia
              Citrullinemia is an inherited disorder that causes ammonia and other toxic substances 
                 to accumulate in the blood. 
       Cause: Mutations in the ASS1 and SLC25A13 genes cause citrullinemia. The proteins produced from these genes play roles in the urea cycle.
      
Two types of citrullinemia have been described; they have different signs and symptoms and are caused by mutations in different genes.

     **Type I citrullinemia** (also known as classic citrullinemia)
      **Type II citrullinemia** chiefly affects the nervous system, causing confusion, restlessness, memory loss, abnormal behaviors (such as aggression, irritability, and hyperactivity), seizures, and coma
  
  **current set of xrefs:**
UMLS_CUI:C0175683
OMIM:605814
SNOMEDCT_US_2018_03_01:15489004
OMIM:215700
MESH:D020159
CSP2005:1849-9492
NCI:C84639
OMIM:603471
ORDO:187
ICD10CM:E72.23

**Child term request:**
for OMIM:215700, OMIM:603471, OMIM:605814.

**OMIM:215700**. - classic citrullinemia
    -- caused by homozygous or compound heterozygous mutation in the ASS1 gene, which encodes argininosuccinate synthetase, on chromosome 9q34.

**OMIM:605814** -   neonatal-onset type II citrullinemia
   also known as neonatal intrahepatic cholestasis caused by citrin deficiency (NICCD), is caused by homozygous or compound heterozygous mutation in the SLC25A13 gene.

--> Looking up synonym in DO - intrahepatic cholestasis.  DOID:1852
          --> need to add a definition: 
         NCI xref:  NCI:C84400
          Preferred Name:  Intrahepatic Cholestasis
          Definition:  Impairment of the bile flow caused by obstruction within the liver.
           
  GARD:10214
       Neonatal intrahepatic cholestasis caused by citrin deficiency (NICCD) is a liver condition is also known as neonatal-onset type II citrullinemia. NICCD blocks the flow of bile (a digestive fluid produced by the liver) and prevents the body from processing certain nutrients properly.


**OMIM:603471**
adult-onset type II citrullinemia, also known as citrin deficiency, is caused by homozygous or compound heterozygous mutation in the SLC25A13 gene  on chromosome 7q21.

**Comment by melodyswen** [comment]
Child terms have been added

**Comment by melodyswen** [comment]
Added definition to DOID:1852 and has_exact synonym neonatal intrahepatic cholestasis
