### ISSUE TITLE
Update SARS-CoV-2 organism term 

### ISSUE THREAD

**Issue by FuqiX** [DiseaseOntology/HumanDiseaseOntology#839]
HDO has included Term [Wuhan seafood market pneumonia virus](https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_2697049)

- The original [NCBI taxonmy](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2697049) provided more synonyms to this term. Could you please and more synonyms
- the standard name for coronavirus19 is _Severe acute respiratory syndrome coronavirus 2_ Would it be better to the official name?

Thanks a lot!

**Comment by lschriml** [comment]
Thank you for the request. 
   We have now added all of the synonyms. 
And committed the updated file to our GitHub. 

We had been delayed on adding the most recent term, as our source file (from http://www.obofoundry.org/ontology/ncbitaxon.html), did not yet include the most up to date name.
  Rather than delay, we have. made the name change based on NCBI taxonomy database:
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi

The changes will be made public today.

Please let us know if we can be of further assistance.

Cheers,
Lynn Schriml
