### ISSUE TITLE
psoriasis terms

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#855]
Hi, we think that 
psoriatic arthritis
should be both a psoriasis and also an 
autoimmune disease   of skin and connective tissue
This is how we see it being described in the literature. Thanks

**Comment by lschriml** [comment]
Thank you for all of the new terms to review for the DO Randi !!
I will review.

Cheers,
Lynn

**Comment by lschriml** [comment]
Have added these terms into a google doc, to record review notes.
https://docs.google.com/spreadsheets/d/1I9Vz3YxMocxvcBXwIviqQGgOZZL_7ESOovjhSKOXYjM/edit#gid=0

Shared with @rvita @beckyjackson

**Comment by lschriml** [comment]
GHR: https://ghr.nlm.nih.gov/condition/psoriatic-arthritis

Psoriatic arthritis is a condition involving joint inflammation (arthritis) that usually occurs in combination with a skin disorder called psoriasis.

is_a arthritis 
is_a (inferred) autoimmune disease of skin and connective tissue

**Comment by rvita** [comment]
These psoriasis terms are reasoning as children of autoimmune disease instead of children of autoimmune disease of skin and connective tissue.

**Comment by beckyjackson** [comment]
We'd like to follow up on this ticket. We think that the placement of these two terms are still slightly off:

| Term ID | Label | Current Parents | Expected Parent(s) |
| --- | --- | --- | --- |
| DOID:8893 | psoriasis | autoimmune disease*, skin disease | autoimmune disease of skin and connective tissue |
| DOID:9008 | psoriatic arthritis | autoimmune disease of skin and connective tissue*, arthritis | psoriasis, arthritis |

The current parents with a \* next to them are the inferred parents. I think for 'psoriasis', we can just move it from "skin disease" to "autoimmune disease of skin and connective tissue"?

For psoriatic arthritis, it's a bit more difficult since neither arthritis nor psoriasis have equivalent axioms. The easy fix is to just add two named parents. The more difficult fix would be to write an equivalent axiom for one of these diseases, but I'm not sure that that is possible.

**Comment by lschriml** [comment]
I've updated psoriasis to be a child of autoimmune disease of skin and connective tissue.
I think it should be is_a skin disease.

psoriatic arthritis is not is_a psoriasis

see: 
GHR: https://ghr.nlm.nih.gov/condition/psoriatic-arthritis

Psoriatic arthritis is a condition involving joint inflammation (arthritis) that usually occurs in combination with a skin disorder called psoriasis.

is_a arthritis
is_a (inferred) autoimmune disease of skin and connective tissue

Cheers,
Lynn
