### ISSUE TITLE
IEDB Term Request Ticket

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#874]
We have some new term requests or synonym requests for Past medical History (PMH) forms used in HIPC clinical projects.
[AdultPMH_DO_term_requests.xlsx](https://github.com/DiseaseOntology/HumanDiseaseOntology/files/4702791/AdultPMH_DO_term_requests.xlsx)
Thanks,
Randi

**Comment by lschriml** [comment]
Regarding:
parentage, new terms: 
   -- axioms added where requested
two new terms in tickets: 850 and 851


Regarding: 
Adult PMH_DO_term_requests
- autoimmune hypersensitivity disease --> term name changed to 'autoimmune disease' 
- autoimmune cardiomyopathy --> request synonym autoimmune myocarditis
        cardiomyopathy: disease of heart muscle
        myocarditis: inflammation of the heart muscle
               --> these are not synonymous
                       --> we could create a new DO term: 'autoimmune myocarditis' 

- proctitis 
                     --> request synonym ulcerative proctitis
                             --> this term was previously obsoleted in the DO.
             Reviewing 'ulcerative proctitis' --> I see that is an anatomical subtype of 
                              ulcerative colitis
                  --> If you like, I could bring 'ulcerative proctitis' back from 'obsolete'

- acute disseminated encephalomyelitis
                 --> request synonym: 
                             --> Post Infectious Encephalitis
                               -- this term was previously obsoleted in the DO

               -- reviewing the term, I found that it is a subtype of encephalitis:
Secondary encephalitis. This condition results from a faulty immune system reaction to an infection elsewhere in the body. Instead of attacking only the cells causing the infection, the immune system also mistakenly attacks healthy cells in the brain. Also known as post-infection encephalitis, secondary encephalitis often occurs two to three weeks after the initial infection.
https://www.mayoclinic.org/diseases-conditions/encephalitis/symptoms-causes/syc-20356136

--> I can revive this term, add it as a child of 'encephalitis' and 'autoimmune disease'
         as a child of 'autoimmune neuropathy' 

Cheers,
Lynn

**Comment by lschriml** [comment]
Terms added, - two spreadsheets updated with curation notes. Curation complete.

a few terms need further feedback from @rvita 
  listed  in previous comment. 
-

**Comment by rvita** [comment]
For: acute disseminated encephalomyelitis
--> request synonym:
--> Post Infectious Encephalitis
you stated
--> I can revive this term, add it as a child of 'encephalitis' and 'autoimmune disease'
as a child of 'autoimmune neuropathy'
I agree, that sounds good to me.

**Comment by lschriml** [comment]
Added to DO.

**Comment by rvita** [comment]
Hi, I do not see anything regarding the 14 new term requests on the tab called "new term"? Are those on a different ticket?
Thanks,
Randi

**Comment by beckyjackson** [comment]
Hi @lschriml - we still need the following terms for IEDB. If they look acceptable, I can add them in! I'm not sure about the parentage on the first two. Thank you!

| Label | Parent |
| --- | --- |
| solid tumor without metastasis | benign neoplasm ? |
| metastatic cancer | cancer ? |
| spondyloarthritis | autoimmune hypersensitivity disease |
| cytomegalovirus | viral infectious disease |

**Comment by lschriml** [comment]
Thank you Becky, I will review and add them.
Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Becky,
  Looking at the [IEDB DO Google doc ](https://docs.google.com/spreadsheets/d/1uXadxhDMsW-lMhb9S68E4ZgnCfA10kFINkgOCsrNv7Q/edit#gid=0)for these terms:

solid tumor without metastasis   --> not a disease term, I would suggest mapping to 'cancer' DOID:162

metastatic cancer --> not a specific disease, DO doesn't include metastasis

spondyloarthritis --> Not a disease, rather: Spondyloarthritis (SpA) is the umbrella term for a broad spectrum of inflammatory rheumatic diseases

cytomegalovirus --> This is not a specific disease 
                                    This is a group of viruses (in the order Herpesvirales)

Cheers,
Lynn

**Comment by rvita** [comment]
Thanks, we will discuss today & get back to you soon.
