### ISSUE TITLE
NTR  Noonan syndrome-like disorder with loose anagen hair 1 #607721   

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#878]
OMIM #607721 
PMID: 28211982
PMID:30329053
Noonan syndrome-like disorder with loose anagen hair is characterized by facial features similar to those observed in Noonan syndrome, including hypertelorism, ptosis, downslanting palpebral fissures, low-set posteriorly angulated ears, and overfolded pinnae. In addition, patients display short stature, frequently with growth hormone deficiency; cognitive deficits; relative macrocephaly; small posterior fossa resulting in Chiari I malformation; hypernasal voice; cardiac defects, especially dysplasia of the mitral valve and septal defects; and ectodermal abnormalities, in which the most characteristic feature is the hair anomaly, including easily pluckable, sparse, thin, slow-growing hair (summary by Bertola et al., 2017). 
is_a syndrome DOID:225
has_symptoms_of  cardiovascular system disease DOID:1287 (mitral valve, septal defects,  coagulopathy, hypertrophic cardiomyopathy)
has_symptoms_of integumentary system disease DOID:16 (hair disease, hyper-pigmentation, eczema or ichthyosis)

**Comment by lschriml** [comment]
Thank you Ceri for this new DO term !!

I have added these two new terms.

Cheers,
Lynn

**Notes:** 
Looking at this term:
OMIM: 607721. Noonan syndrome-like disorder with loose anagen hair 1
PMID: https://pubmed.ncbi.nlm.nih.gov/25137548/
PMID:30329053


I see there is a second Noonen-like OMIM:
      **OMIM:617506. Noonan syndrome-like disorder with loose anagen hair 2**
        PMID: https://pubmed.ncbi.nlm.nih.gov/27264673/
                    https://pubmed.ncbi.nlm.nih.gov/28211982/

 Noonan syndrome with loose anagen hair (NS-LAH) is characterized by its distinctive hair anomalies, developmental differences, and structural brain abnormalities and is caused by a single recurrent missense SHOC2 mutation. SHOC2 forms a complex with protein phosphatase 1 (PP1C). Protein phosphatases counterbalance kinases and control activation of signaling proteins, such as the mitogen-activated protein kinases of the RAS/MAPK pathway. Here we report four patients with de novo missense mutations in protein phosphatase one catalytic subunit beta (PPP1CB), sharing a recognizable phenotype. Three individuals had the recurrent PPP1CB c.146G>C, p.Pro49Arg mutation, the fourth had a c.166G>C, p.Ala56Pro change. All had relative or absolute macrocephaly, low-set and posteriorly angulated ears, and developmental delay. Slow growing and/or sparse hair and/or an unruly hair texture was present in all. 


Orphanet (ORPHA:2701) and GARD (GARD:10719). - includes both OMIMs.
