### ISSUE TITLE
'autoimmune disease of eyes, ear, nose and throat' placement

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#894]
the term 'autoimmune disease of eyes, ear, nose and throat'
is currently a child of 
'autoimmune disease of the nervous system'
when it should be a sibling instead.
Thanks

**Comment by lschriml** [comment]
Hello Randi,
    both terms are asserted is_a 'autoimmune disease' 
--> they are sibling terms. 

The EQ statements for each term, below, defining Inferred parents, makes AD eyes, etc a child of AD nervous system, 
 since sensory system is a child of nervous system 

EQ: 
for 
    autoimmune disease of eyes, ear, nose and throat
      is   --> 'autoimmune disease' and ('located in' some 'sensory system')

for 
   'autoimmune disease of the nervous system'
  is  --> 'autoimmune disease' and ('located in' some 'nervous system')

--> 
Since AD eyes, etc.  has no 'inferred child terms, I am removing it's EQ, to remove this parentage problem.

Cheers,
Lynn
