### ISSUE TITLE
Add terms to cancer slim file

### ISSUE THREAD

**Issue by kkrysiak** [DiseaseOntology/HumanDiseaseOntology#905]
We've identified a series of terms that are not in the cancer slim file that would benefit CIViC's use of DO.

6785 - desmoplastic small round cell tumor
0060103 - central nervous system primitive neuroectodermal neoplasm

**Comment by lschriml** [comment]
Hello KK,
Please send them all to me and I will add them tomorrow.
Do you need any new terms added to DO ?
Cheers,
Lynn

**Comment by kkrysiak** [comment]
Yeah, sorry, I didn't mean to have them sprinkle in like that but it's been an evolving identification. That's partly why I wanted to just create a new github issue where we can add them here. I'll add some now and try to catch up to add more later this evening.

I'm sure we have some additional terms as well. 
- Sinonasal undifferentiated carcinoma (NCIt: C54294)
- Salivary Gland Mucinous Adenocarcinoma (NCIt: C62193)
- Glioma (C3059)
- Pediatric low grade glioma (there is not a term specific to pediatric but LGG in NCIt: C132067)

**Comment by lsheta** [comment]
thyroid gland anaplastic carcinoma (DOID: 0080522)

**Comment by lsheta** [comment]
Childhood Acute Megakaryoblastic Leukemia (NCIt: C7972)
Acute Basophilic Leukemia (NCIt: C3164)
Core Binding Factor Acute Myeloid Leukemia (NCIt: C122688)
Nasal Type Extranodal NK/T-Cell Lymphoma (NCIt: C4684) 
Glioblastoma (NCIt: C3058)
Myeloid Leukemia Associated with Down Syndrome (NCIt: C43223)

**Comment by kkrysiak** [comment]
So 9953 has "B- and T-cell mixed leukemia" as an exact match. I feel like this should be a child concept since mixed lineage leukemia could be myeloid/lymphoid or multiple lymphoid lineages.

**Comment by lsheta** [comment]
Mammary Analogue Secretory Carcinoma (MASC; seems like it belongs but no NCIt code, has an NCIm page: https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI Metathesaurus&code=C4042906)

**Comment by lschriml** [comment]
added to DO cancer slim subset:
 
     6785 - desmoplastic small round cell tumor
     0060103 - central nervous system primitive neuroectodermal neoplasm

Added: DOID:0080794       
             Childhood Acute Megakaryoblastic Leukemia (NCIt: C7972)
             
Added: DOID:0080795 
             Acute Basophilic Leukemia (NCIt: C3164)

Added: DOID:0080796 
            Core Binding Factor Acute Myeloid Leukemia (NCIt: C122688)

Added: DOID:0080797
         Nasal Type Extranodal NK/T-Cell Lymphoma (NCIt: C4684)

Glioblastoma (NCIt: C3058)
   --> in DO, this is glioblastoma multiforme DOID:3068
        - already in the slim 

Added: DOID:0080798
          Myeloid Leukemia Associated with Down Syndrome (NCIt: C43223)

Added: DOID:0080799
     Sinonasal undifferentiated carcinoma (NCIt: C54294)
       --> sinonasal is a combination of : Nasal Cavity and Paranasal Sinus 
       --> In DO, we do not have sinonasal as a distinct anatomical entity
           So, to add this term, I will add it as both a child of nasal cavity carcinoma and paranasal sinus cancer

Added: DOID:0080800
         Salivary Gland Mucinous Adenocarcinoma (NCIt: C62193)

Glioma (C3059)
     --> Note: this NCI term is benign or malignant
            DO has 'benign glioma' and 'malignant glioma'  (NCIt:4822)
             'malignant glioma' is in the DO cancer slim subset

To Do: 
Pediatric low grade glioma (there is not a term specific to pediatric but LGG in NCIt: C132067)
thyroid gland anaplastic carcinoma (DOID: 0080522)

**Comment by kkrysiak** [comment]
I agree we should put `glioblastoma` under `glioblastoma multiforme` but I would argue that the simpler term should be changed to the main term in DO. The updated WHO and NCCN guidelines are referring to them as simply glioblastoma now. Similarly, the cIMPACT-NOW group use this terminology. These are just my thoughts on it. CNS tumor guidelines have been evolving at a crazy fast pace the last few years so hopefully this is helpful, I don't envy trying to keep up with these (and every other guideline) covered by your resource. Thanks, as always!

**Comment by lschriml** [comment]
Honestly, we couldn't keep up without our fantastic, generous collaborators. 

I've made the update. I really appreciate your sharing the extra info :)

**Comment by lschriml** [comment]
DONE: 

**Pediatric low grade glioma** (there is not a term specific to pediatric but LGG in NCIt: C132067)
  
   **Question:**    
       --> as this a category rather than a specific disease, could the annotation be for one of the types ? 
            e.g. pilocytic astrocytoma

        Notes: 
         --> 2009 paper
                 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2917804/
         
        -  Pediatric low-grade gliomas encompass a heterogeneous set of tumors of different histologies. 
           They encompass tumors of astrocytic, oligodendroglial, and mixed glial-neuronal histology.    
        
           types: Cerebellar pilocytic astrocytoma, supratentorial diffuse fibrillary astrocytomas



      Low-Grade Glioma in Children
       http://www.danafarberbostonchildrens.org/conditions/brain-tumor/low-grade-glioma.aspx

         Low-grade gliomas are brain tumors that originate from glial cells, which support and nourish neurons in the brain. Glial tumors, or gliomas, are divided into four grades, depending on their cells' appearance under a microscope. Grade 1 and 2 gliomas are considered low-grade and account for about two-thirds of all pediatric tumors.
The most common kind of low-grade glioma, called a pilocytic astrocytoma, has a cure rate over 90 percent.

=================================
 [Added to DO, DOID:0080808]
Mammary Analogue Secretory Carcinoma (MASC; seems like it belongs but no NCIt code, has an NCIm page: https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI Metathesaurus&code=C4042906)

--> publication in 2017
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5643951/
       Mammary analogue secretory carcinoma (MASC) is a newly defined entity among salivary gland malignancies which has just been established in the 4th edition of the WHO classification of head and neck tumors. MASC (synonym: secretory carcinoma) are characterized by a specific rearangement of the ETV6 gene locus.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7113190/

Secretory carcinoma is a salivary gland tumor with a characteristic chromosomal translocation that results in an ETV6-NTRK3 fusion gene.
ETV6 translocation

http://www.pathologyoutlines.com/topic/salivaryglandsmammary.html
==============================

So DOID:9953 has "B- and T-cell mixed leukemia" as an exact match. I feel like this should be a child concept since mixed lineage leukemia could be myeloid/lymphoid or multiple lymphoid lineages (C151992). And perhaps the definition of 9953 could be modified to say either a mix of myeloid/lymphoid or multiple lymphoid lineages.

mixed phenotype acute leukemia [DOID:9953]
    -- the synonym came from MESH
    -- I've removed the synonym 

updated definition:
An acute leukemia that is characterized by the occurrence of more than one type of leukemia at the same time resulting from either the occurrence of blasts which coexpress myeloid and T or B lineage antigens or concurrent B and T lineage antigens. 

 

NCI:
Definition:  An acute leukemia of ambiguous lineage characterized by blasts which coexpress myeloid and T or B lineage antigens or concurrent B and T lineage antigens. (WHO, 2001)

NICHD Definition:  An acute leukemia characterized by a single population of blasts that coexpress myeloid and lymphoid antigens.

[Wikipedia: https://en.wikipedia.org/wiki/Biphenotypic_acute_leukaemia]
arises in multipotent progenitor cells which have the ability to differentiate into both myeloid and lymphoid lineages



===========================
thyroid gland anaplastic carcinoma (DOID: 0080522), I think this one may just need the tag.
--> added to DO cancer slim

**Comment by kkrysiak** [comment]
I'm sending your query on to the ClinGen Pediatric Taskforce who are best qualified to respond. I hope we receive a response soon, I don't have an immediate answer to your question. 

Thank you for all the help!

**Comment by lschriml** [comment]
Hello KK, @kkrysiak 
   has there been further discussion ? 

Cheers,
Lynn

**Comment by lschriml** [comment]
Notes:
https://docs.google.com/document/d/1vc3Y1jALaZwn0CbJ_ijO6c0LqG7Wb_GK-FeVysZx9SI/edit?usp=sharing

added:
        low-grade glioma 
and pediatric low-grade glioma 
and make
    pilocytic astrocytoma - a child of pediatric low-grade glioma
