### ISSUE TITLE
term request: congenital laryngomalacia

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#910]
This is similar to the renal agenesis (DOID:14766) term
definition: a laryngeal disease characterized by abnormal development of the cartilage of the larynx.
Xref: ICD-10-CM CODE Q31.5
https://rarediseases.info.nih.gov/diseases/6865/laryngomalacia
child of laryngeal disease and congenital disease
also see: http://purl.obolibrary.org/obo/MONDO_0007878
Thanks
--

--

**Comment by lschriml** [comment]
- In literature, the term used is laryngomalacia
DOID:0080833
- Adding laryngomalacia to the DO, as a child of laryngeal disease and a inferred child of physical disorder.
      -  synonym:     congenital laryngomalacia

**laryngomalacia** is an abnormality of the voice box (larynx) that leads to the inward collapse of the airway when air is drawn into the lungs (inspiration). It usually becomes apparent at birth or shortly after birth. The most common symptom is noisy breathing (stridor) that is often worse when the infant is on his/her back or crying.

Laryngomalacia is the most frequent cause of **noisy breathing (stridor)** in infants and children. It is the most common congenital anomaly (birth defect) of the voice box (larynx). Laryngomalacia is best described as floppy tissue above the vocal cords that falls into the airway when the infant breathes in. 
https://www.childrenshospitalvanderbilt.org/medical-conditions/laryngomalacia

Laryngomalacia literally means “Soft Larynx”.
- characterised by inward collapse of flaccid supraglottic structures during inspiration.

    GARD:6865
    ICD10CM:Q31.5
 
-----------------------------------------------
adding: 
**acquired laryngomalacia**
- acquired collapse of laryngeal suprastructures.
- The aetiology of the acquired form includes neurological, traumatic and iatrogenic.
        https://pubmed.ncbi.nlm.nih.gov/24615649/
- 
iatrogenic: relating to illness caused by medical examination or treatment

**Stridor** is a high-pitched, wheezing sound caused by disrupted airflow. Stridor may also be called musical breathing or extrathoracic airway obstruction. 

https://pubmed.ncbi.nlm.nih.gov/1562135/

- https://pubmed.ncbi.nlm.nih.gov/33009823/
- https://pubmed.ncbi.nlm.nih.gov/32278471/
https://pubmed.ncbi.nlm.nih.gov/30554704/


Cheers,
Lynn
