### ISSUE TITLE
pemphigus children

### ISSUE THREAD

**Issue by rvita** [DiseaseOntology/HumanDiseaseOntology#918]
bullous pemphigoid DOID:8506, pemphigoid gestationis DOID:14482 and cicatricial pemphigoid DOID:11656 are reasoning as siblings of pemphigus DOID:9182 instead of as its children.

**Comment by lschriml** [comment]
@rvita  
   Review notes below,
  plan to move terms, subtypes as follows: 

autoimmune disease of skin and connective tissue
        **pemphigus** 
              [subtypes]
               Pemphigus Vulgaris, Pemphigus Foliaceus, Pemphigus Vegetans, IgA Pemphigus, Paraneoplastic 
              Pemphigus, Mucous Membrane Pemphigoid, Bullous Pemphigoid, Gestational Pemphigoid, 
              Epidermolysis Bullosa Acquisita  


       **pemphigoid**
            [subtypes] 
             cicatricial pemphigoid
             bullous pemphigoid
             pemphigoid gestationis



connective tissue disease
                  is_a    **bullous skin disease** - An autoimmune disease of skin and connective tissue that is 
                                                             characterized by blisters filled with a watery fluid, located_in skin. 
                                                             The disease is associated with the amount of gluten ingested. 
 
                                                          bullous: characterized by blisters or bullae on the skin.
         --> REVISE Definition: NOT an autoimmune disease 
               REVISE: Definition xref 
              [subtypes]
                  dermatitis herpetiformis
                  subcorneal pustular dermatosis


NOTES:


NORD: https://rarediseases.org/rare-diseases/pemphigus/

**Pemphigus** affects the outer of the skin (epidermis) and causes lesions and blisters that are easily ruptured. **Pemphigoid** affects a lower layer of the skin, between the epidermis and the dermis, creating tense blisters that do not break easily.

**Pemphigus and pemphigoid** are **rare autoimmune blistering diseases of the skin and/or mucous membranes.** 

The term “pemphigus” is used in a very specific way to describe blistering disorders caused by autoantibodies such as desmoglein 1 and desmoglein 3 that recognize components of the epidermis and lead to disruption of the intercellular junctions, loss of integrity, and formation of blisters.

Pemphigoid is a group of subepidermal, blistering autoimmune diseases that primarily affect the skin, especially in the lower abdomen, groin, and flexor surfaces of the extremities. Here, autoantibodies (anti-BPA-2 and anti-BPA-1) are directed against the basal layer of the epidermis and mucosa.

dermitis
     is_a **bullous skin disease** 
                     bullous: characterized by blisters or bullae on the skin.



          is_a  **pemphigus** - A bullous skin disease that is characterized by blistering of the skin and mucous 
                                              membranes (mouth, nose, throat, eyes, and genitals).
                                   [GARD] Pemphigus is a group of rare autoimmune diseases that cause blistering of the  
                                                 skin and mucous membranes (mouth, nose, throat, eyes, and genitals)
                                              There are four main types of pemphigus:[2]

                                   Pemphigus vulgaris, Pemphigus foliaceus, IgA pemphigus, Paraneoplastic pemphigus

                **cicatricial pemphigoid** (DOID:11656) - A bullous skin disease characterized by skin lesions and scaring 
                                            and located_in mucous membranes and located_in skin.
                                    [GARD] **Mucous membrane pemphigoid** is a rare, chronic, blistering and scarring 
                                                    disease  that affects the oral and ocular mucosa. 
                                                 Although the specific causes of this condition have not been identified, it is 
                                                 considered an autoimmune disease that is characterized by the production of 
                                                 autoantibodies against basement membrane zone antigens such as BP180, 
                                                 BP230, and laminin 5

**bullous pemphigoid**  (DOID:8506) - An autoimmune disease of skin and connective tissue characterized 
                                                                   by large blisters.
**pemphigoid gestationis** (DOID:14482) - An autoimmune disease of skin and connective tissue that is 
                                      characterized by blistered skin as a result of self-reactive T and B cells that target BP180.

**Comment by rvita** [comment]
sorry, it is hard for me to follow. What terms will not be an autoimmune disease? Will bullous pemphigoid and pemphigoid gestationis be children of autoimmune disease?

**Comment by lschriml** [comment]
Hello Randi,
 upper most parent : autoimmune disease of skin and connective tissue
       child term: pemphigus
              with [subtypes]
                       Pemphigus Vulgaris, Pemphigus Foliaceus, Pemphigus Vegetans, IgA Pemphigus, Paraneoplastic
                        Pemphigus, Mucous Membrane Pemphigoid, Bullous Pemphigoid, Gestational Pemphigoid,
                         Epidermolysis Bullosa Acquisita
      
       child term: pemphigoid
             with  [subtypes] 
                      cicatricial pemphigoid
                      bullous pemphigoid
                      pemphigoid gestationis

**Comment by rvita** [comment]
great, thanks!

**Comment by lschriml** [comment]
requested terms are updated.

New terms to review: 
 Pemphigus foliaceus, IgA pemphigus, Paraneoplastic pemphigus

**Comment by lschriml** [comment]
Added: Pemphigus foliaceus, IgA pemphigus, Paraneoplastic pemphigus
