### ISSUE TITLE
Automated check - axiom, imports

### ISSUE THREAD

**Issue by lschriml** [DiseaseOntology/HumanDiseaseOntology#919]
@beckyjackson -- a few cases in the current file have been identified where an axiom has been defined, where there are terms in common between the DO and an import. 
We do not always catch these duplications while creating axioms. 

E.g. diarrhea, myocarditis

I would like to create a curation queue when this happens, so that we can identify when protege selects a DO term in the axiom rather than an import term.
e.g. 
'has symptom' some diarrhea
   - where diarrhea is both in SYMP and in DO
   - here we want the SYMP term 

Can we be even more specific? 
  Check that 'has symptom' axioms only include terms from the SYMP ontology
                       has_phenotype from HPO

Cheers,
Lynn

**Comment by beckyjackson** [comment]
We can definitely do this, but this is always going to be an issue in Protege when we have the labels the same as another term. In order to differentiate, we should make sure all labels are unique and update cases where labels overlap. For diarrhea, we should decide a way in the label to designate symptom vs. disease. Shouldn't diarrhea always be a symptom, though, as it's caused by a disease?

**Comment by beckyjackson** [comment]
Maybe since "diarrhea" is a grouping term in DOID, it should be "diarrheal disease", like in this WHO page - https://www.who.int/news-room/fact-sheets/detail/diarrhoeal-disease

**Comment by lschriml** [comment]
Good idea, I’ll check it out.
