### ISSUE TITLE
NTR:  ocular motor apraxia OMIM:257550

### ISSUE THREAD

**Issue by cerivs** [DiseaseOntology/HumanDiseaseOntology#923]
Definition: Ocular motor apraxia (OMA) is the absence of, or a defect in, the control of voluntary, purposeful eye movement.  The quick, simultaneous movement of both eyes in the same direction (saccades) on the horizontal plane are abnormal.
Source:https://aapos.org/glossary/oculomotor-apraxia

OMIM:257550

is_a  ocular motility disease DOID:1279

NTR  congenital ocular motor apraxia: Congenital defect in, the control of voluntary, purposeful horizontal eye movement.  Defective initiation of horizontal saccades and saccade hypometria with normal saccadic velocity. Differs from Joubert syndrome and ataxia telangiectasia in that only horizontal not vertical eye movement affected. 
Synonyms" Infantile-onset saccade initiation delay, COMA
is_a ocular motor apraxia
https://link.springer.com/article/10.1007/s11910-015-0543-3

**Comment by cerivs** [comment]
OMIM says may be dominant.  Zebrafish model (different gene) is recessive.    AAPOS suggests  that it can be either genetic (sporadic or inherited) or environmental in origin.

**Comment by lschriml** [comment]
Thank you for the new term.
We will review and add to DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
Adding as a child of eye disease: 
ocular motor apraxia, Cogan type

Notes: 
https://rarediseases.org/rare-diseases/ocular-motor-apraxia-cogan-type/
https://eyewiki.aao.org/Oculomotor_Apraxia
https://rarediseases.info.nih.gov/diseases/16/oculomotor-apraxia-cogan-type
https://en.wikipedia.org/wiki/Oculomotor_apraxia
https://omim.org/entry/257550

https://www.orpha.net/consor/cgi-bin/Disease_Search.php?
lng=EN&data_id=1404&Disease_Disease_Search_diseaseGroup=1125&Disease_Disease_Search_diseaseType=ORPHA&Disease(s)/group%20of%20diseases=Ocular-motor-apraxia--Cogan-type&title=Ocular%20motor%20apraxia,%20Cogan%20type&search=Disease_Search_Simple
ORDO:1404

OMIM:Congenital oculomotor apraxia, first reported by Cogan (1952), is characterized by (1) defective or absent horizontal voluntary eye movements, and (2) defective or absent horizontal ocular attraction movements.
OMIM, Inheritance: AR


ocular motor apraxia
    - Idiopathic congenital OMA has been coined “Cogan-type” and presents with symptoms during the first year of life. 
    - synonym: Cogan-type OMA
    - 
Oculomotor apraxia Cogan type (COMA) is an eye condition characterized by a defect in side-to-side (horizontal) eye movements.
    
Cogan type ocular motor apraxia is a rare congenital disorder characterized by a defect in side-to-side (horizontal) eye movements. The eyes do not move properly in response to stimuli or voluntarily. When affected infants are asked to fixate on an object to the side, their eyes will lag and then move in the opposite direction. In order to compensate for this, the infants will sharply jerk their heads past the desired object in an effort to bring the eyes to a position where they can view the object. When the eyes fixate on the object, the head will return to its normal position. 


    - In addition to horizontal OMA, these children also often have developmental delay, hypotonia, and speech problems
    - Children with congenital OMA have difficulty fixating on targets and may initially be mistaken as blind. Once head control is established—usually by 6 months of age—an affected child will begin to exhibit head thrusting in order to fixate on an object that has their attention. Head thrusting turns the head well past the object of interest, activating the vestibulo-ocular reflex as fluid in the semicircular canals stimulates eye movement in the direction of the thrust. Once the object is in view, the head is then turned back to its normal position

Acquired OMA
