### ISSUE TITLE
Add 'hemolytic anemia' as parent of 'autoimmune hemolytic anemia'

### ISSUE THREAD

**Issue by allenbaron** [DiseaseOntology/HumanDiseaseOntology#956]
"autoimmune hemolytic anemia" (DOID:718) is a child of "autoimmune disease of blood" (DOID:0060050) but not "hemolytic anemia" (DOID:583).

Consider adding the parent relationship to "hemolytic anemia".

**Comment by allenbaron** [comment]
"hemolytic anemia due to glutathione synthetase deficiency" (DOID:0112252) also does not appear to be a child of DOID:583. A closer review of the descendants of hemolytic anemia might be in order.

**Comment by lschriml** [comment]
Agreed, the parentage needs augmenting: 
Since there is no EQ for hemolytic anemia,
 one way to have 'autoimmune hemolytic anemia' be a child of both 'hemolytic anemia' and 'autoimmune disease of blood' is to update the is_a parentage to
hemolytic anemia, and add the subclassof axiom: 'has phenotype' some 'Abnormal immunoglobulin level', and  and ('disease has location' some blood) thus defining the inferred parentage. 

--> updated in the DO

**Comment by lschriml** [comment]
-- updated in the DO

-- review: 
"hemolytic anemia due to glutathione synthetase deficiency" (DOID:0112252) is not a child of DOID:583.
    -- this is a glutathione synthetase deficiency, that results in hemolytic anemia (among other things).
    -- the confusion is in the way the disease was initially named.
    -- updated disease name:
                  glutathione synthetase deficiency of erythrocytes

Notes: 

"hemolytic anemia due to glutathione synthetase deficiency" (DOID:0112252)
     --> to review this term, and if it should be a child of 'hemolytic anemia'
          -- looking at OMIM, Orphanet, publications to look at current information for this disease.
        - Wondering if there has been a nomenclature update or refinement of the disease classification. 
        
        -  Reading through the DO definition, looks like this is a type of glutathione synthetase deficiency, that results in hemolytic anemia and GSH deficiency.

OMIM: 
There are two forms of this glutathione deficiency:
(1) a mild form, referred to as glutathione synthetase deficiency of erythrocytes, causing hemolytic anemia
    OMIM:231900.  ( Inheritance: autosomal recessive) 
   
     Inheritance: autosomal recessive

        ORDO: 289849 (Glutathione synthetase deficiency without 5-oxoprolinuria) - no definition yet in Orphanet

      GARD:10047 (linked from ORDO:32)
    -- describes the parent term, glutathione synthetase deficiency

(2) a more severe form causing 5-oxoprolinuria with secondary neurologic involvement 
   OMIM:266130. -  Inheritance: autosomal recessive
          - by homozygous or compound heterozygous mutation in the gene encoding glutathione synthetase (GSS) on chromosome 20q11
          - Glutathione synthetase deficiency, or 5-oxoprolinuria, is an autosomal recessive disorder characterized, in its severe form, by massive urinary excretion of 5-oxoproline, metabolic acidosis, hemolytic anemia, and central nervous system damage. The metabolic defect results in decreased levels of cellular glutathione, which overstimulates the synthesis of gamma-glutamylcysteine and its subsequent conversion to 5-oxoproline (Larsson and Anderson, 2001).
          - 
          -  [https://pubmed.ncbi.nlm.nih.gov/15990954/]
          - GSS deficiency is inherited autosomal recessively, and patients with this disease can be divided into three groups, according to their clinical phenotype. Mildly affected patients have mutations affecting the stability of the enzyme, causing a compensated haemolytic anaemia; moderately affected patients have, in addition, metabolic acidosis; and severely affected patients also develop neurological defects and show increased susceptibility to bacterial infections.

  ORDO:32 (called glutathione synthetase deficiency, links to both OMIM IDs, but with a definitions that aligns to OMIM:231900)
      ORDO definition: A rare disorder characterised by hemolytic anemia, associated with metabolic acidosis and 5-oxoprolinuria in moderate forms, and with progressive neurological symptoms and recurrent bacterial infections in the most severe forms.
     Age of onset: neonatal
  


Before making these updates, checking for more up to date literature, PubMed

https://pubmed.ncbi.nlm.nih.gov/34791353/
Glutathione synthetase (GSS) deficiency is a rare disorder, occurring with a frequency of less than 1 in 100,000 individuals worldwide. The clinical presentation may vary from mild to severe, and manifestations include hemolytic anemia, hyperbilirubinemia, metabolic acidosis, neurological problems, and sepsis.

[https://pubmed.ncbi.nlm.nih.gov/29340523/]
Glutathione synthetase deficiency (GSSD) is a rare inborn error of glutathione metabolism with autosomal recessive inheritance. 

The severe form of the disease is characterized by acute metabolic acidosis, usually present in the neonatal period with hemolytic anemia and progressive encephalopathy.

[    [https://pubmed.ncbi.nlm.nih.gov/28267090/]]
  Isolated hemolysis or hemolytic anemia and 5-oxoprolinuria are 2 distinct medical conditions in the clinical spectrum associated with glutathione synthetase deficiency.

**Comment by lschriml** [comment]
To do: add definitions for revised (in 2018) anemia classification.
