### ISSUE TITLE
Cowden syndrome, OMIM:PS158350 and Bannayan-Riley-Ruvalcaba syndrome

### ISSUE THREAD

**Issue by jrsjrs** [DiseaseOntology/HumanDiseaseOntology#971]
It would be very helpful if Cowden syndrome (DOID:6457) could be expanded to match the OMIM phenotypic series OMIM:PS158350 (https://www.omim.org/phenotypicSeries/PS158350) and if the relationship of that series to Bannayan-Riley-Ruvalcaba syndrome (BRRS, DOID:0050657) could be clarified.  As you know, OMIM has merged BRRS with their single entry COWDEN SYNDROME 1; CWS1 (#158350) and made it one of the members of PS158350, versus the fact the DO has only two terms, Bannayan-Riley-Ruvalcaba syndrome (DOID:0050657) and Cowden syndrome (DOID:6457), which have no relationship other than sharing two high-level parent terms (syndrome and sutosomal dominant disease).  Thank you!

**Comment by lschriml** [comment]
Thank you for submitting this review !!
The name changes, lumping and splitting makes this one rather complicated.

Reviewing OMIM, and recent literature, I am going to revise the classification of these syndromes as: 

[parent term]
      **PTEN hamartoma tumor syndrome** [DOID:0080191]
             OMIM:  PS158350
           https://rarediseases.info.nih.gov/diseases/12800/index

[child terms]        
              - Proteus syndrome

and 
              **Cowden syndrome**    [DOID:6457]   
                   xrefs:  
                    GARD:6202. -  Cowden syndrome
                    MESH:D006223    
                       Hamartoma Syndrome, Multiple -  includes: Bannayan-Zonana Syndrome and  Cowden Disease
                    NCI:C3076 - Cowden syndrome
                  NCI:C8419. - Dysplastic Cerebellar Gangliocytoma (Lhermitte-Duclos Disease)

                  ORDO:201. Cowden syndrome
                              SNOMEDCT_US_2020_09_01:58037000   Cowden syndrome
                             SNOMEDCT_US_2020_09_01:67944007          Lhermitte-Duclos Disease
                             UMLS_CUI:C0018553
                            UMLS_CUI:C0391826

      [child terms of Cowden syndrome]
           Bannayan-Riley-Ruvalcaba syndrome   (BRRS,  DOID:0050657) - OMIM:158350
                synonym = Cowden syndrome 1
                        Cowden syndrome-1 (CWS1) is caused by heterozygous germline mutation in the PTEN gene 
                       on chromosome 10q23.

         **Cowden syndrome subtypes ( 4, 5, 6,7)**
 OMIM:615107  Cowden syndrome 4.  
OMIM:615108  Cowden syndrome 5
OMIM:615109  Cowden syndrome 6
OMIM:616858  Cowden syndrome 7.   AD

====================================================
Notes: 
**Cowden syndrome (DOID:6457)**
     A syndrome characterized by multiple noncancerous, tumor-like growths (hamartomas) and an increased risk of certain forms of cancer, especially breast, thyroid and endometrium.
     OMIM:  PS158350

OMIM:158350  Cowden syndrome 1     AD
        in OMIM also: Lhermitte-Duclos syndrome
                       --> OMIM. includes Bannayan-Riley-Ruvalcaba syndrome (BRRS)  
                         as a synonym of Cowden syndrome 1, 4, 5,6,7
                  

Cowden syndrome-1 is a hamartomatous disorder characterized by macrocephaly, facial trichilemmomas, acral keratoses, papillomatous papules, and an increased risk for the development of breast, thyroid, and endometrial carcinoma. Bannayan-Riley-Ruvalcaba syndrome (BRRS), previously thought be distinct, shared clinical characteristics with Cowden syndrome, such as hamartomatous polyps of the gastrointestinal tract, mucocutaneous lesions, and increased risk of developing neoplasms, but had the additional features of developmental delay, macrocephaly, lipomas, hemangiomas, and pigmented speckled macules of the glans penis in males. Because features of BRRS and Cowden syndrome have been found in individuals within the same family with the same PTEN mutation, Cowden syndrome-1 and BRRS are considered to be the same disorder with variable expression and age-related penetrance.

https://pubmed.ncbi.nlm.nih.gov/18781191/

**Genetics Home Reference:** 
https://medlineplus.gov/genetics/condition/bannayan-riley-ruvalcaba-syndrome/
Based on these similarities, researchers have proposed that Bannayan-Riley-Ruvalcaba syndrome and Cowden syndrome represent a spectrum of overlapping features known as PTEN hamartoma tumor syndrome instead of two distinct conditions.

see: DOID:0080191
PTEN hamartoma tumor syndrome

A syndrome characterized as a spectrum of disorders (Cowden syndrome, Bannayan-Riley-Ruvalcaba syndrome, PTEN-related Proteus syndrome, and Proteus-like syndrome) caused by germline mutations of the PTEN gene. 

[https://pubmed.ncbi.nlm.nih.gov/31609537/]
PHTS incorporates a number of historical clinical presentations including Bannayan-Riley-Ruvalcaba syndrome, Cowden syndrome, and a macrocephaly-autism/developmental delay syndrome. 



in OMIM: 
Bannayan-Riley-Ruvalcaba syndrome (BRRS, DOID:0050657)
A syndrome that is characterized by macrocephaly, multiple noncancerous tumors and hamartomas, and dark freckles on the penis, and has_material_basis_in heterozygous germline mutation in the PTEN gene on chromosome 10q23.
