### ISSUE TITLE
Problem Loading Ontology into Owlready2

### ISSUE THREAD

**Issue by rterryn** [DiseaseOntology/HumanDiseaseOntology#972]
Hi, similar to closed issue #776, I'm getting an error when trying to load the ontology via the following command:

o = get_ontology("https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/src/ontology/doid-merged.owl").load()

Note that, unlike closed issue #776, the error is different overall, and the same whether I use file : doid.owl or file: doid-merged.owl.

---------------------------------------------------------------------------
ExpatError                                Traceback (most recent call last)
owlready2_optimized.pyx in owlready2_optimized.parse_rdfxml()

ExpatError: not well-formed (invalid token): line 90, column 88

The above exception was the direct cause of the following exception:

OwlReadyOntologyParsingError              Traceback (most recent call last)
<ipython-input-15-055deda720c7> in <module>
----> 1 o = get_ontology("https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/src/ontology/doid.owl").load()

/opt/conda/lib/python3.9/site-packages/owlready2/namespace.py in load(self, only_local, fileobj, reload, reload_if_newer, url, **args)
    899         try:     fileobj = urllib.request.urlopen(url or f)
    900         except:  raise OwlReadyOntologyParsingError("Cannot download '%s'!" % f)
--> 901         try:     new_base_iri = self.graph.parse(fileobj, default_base = self.base_iri, **args)
    902         finally: fileobj.close()
    903     elif fileobj:

/opt/conda/lib/python3.9/site-packages/owlready2/driver.py in parse(self, f, format, delete_existing_triples, default_base)
    201       except OwlReadyOntologyParsingError as e:
    202         if len(self) == 0: self._add_obj_triple_raw_spo(self.onto.storid, rdf_type, owl_ontology)
--> 203         raise e
    204 
    205     elif format == "owlxml":

/opt/conda/lib/python3.9/site-packages/owlready2/driver.py in parse(self, f, format, delete_existing_triples, default_base)
    194       try:
    195         if owlready2_optimized:
--> 196           owlready2_optimized.parse_rdfxml(f, objs, datas, insert_objs, insert_datas, _abbreviate, new_blank, default_base)
    197         else:
    198           import owlready2.rdfxml_2_ntriples

owlready2_optimized.pyx in owlready2_optimized.parse_rdfxml()

OwlReadyOntologyParsingError: RDF/XML parsing error in file https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/src/ontology/doid.owl, line 90, column 88.

**Comment by lschriml** [comment]
Hello, 
trying to figure out the error. 
doid.owl file, 
[ln 89] 
[ln 90]
[ln 91]    <owl:AnnotationProperty rdf:about="http://purl.obolibrary.org/obo/doid#DO_FlyBase_slim">
[ln 92]        <rdfs:comment>DO_FlyBase_slim</rdfs:comment>

I am not able to find an error.
Have you uncovered the source of the issue ? 

Cheers,
Lynn

**Comment by whinis** [comment]
I looked into this and I don't know whats breaking exactly but seems to possible be an encoding issue. I added an extra line at line 15 and it starts to load more but then fails to load ext.owl due to a different format. Seems to be some issue with the parser.

**Comment by allenbaron** [comment]
The error is probably due to an expectation by owlready2 that the input to `get_ontology()` be an IRI and DO's IRI is not a Github URL but an OBO Foundry PURL.

As noted in #776, using the PURL to the doid-merged.owl file successfully loads the ontology. 

```python
from owlready2 import *

do = get_ontology("http://purl.obolibrary.org/obo/doid-merged.owl").load()
obo = do.get_namespace("http://purl.obolibrary.org/obo/")
```

However, the [published example programs](http://www.lesfleursdunormal.fr/static/_downloads/article_owlready_aim_2017.pdf) for the Gene Ontology (GO) (Fig. 5 & 6), which should would work for DO, only return empty values (example: `print(obo.DOID_4)` returns "None").

owlready2 _can_ be made to work with DO in a limited fashion with a workaround that introduces the doid.owl base IRI:
```python
get_ontology("http://purl.obolibrary.org/obo/doid.owl").load()
```

This errors out but, after executing this code, `print(obo.DOID_4)` returns "obo.DOID_4" as expected. However, DO classes are still not accessible via the `.classes()` method (i.e. `for c in doid.classes(): print(c)` does not print anything).


## Potential Fix
A solution on our end would be to reformat ext.owl to standard RDF/XML format. I tested this locally and it fixes the problems. I do not know what problems, if any, it might produce when creating releases.

<details>
<summary><strong>Code</strong></summary>

_Should be executed from HumanDiseaseOntology top-level directory._

Convert to RDF/XML:
```bash
mv src/ontology/ext.owl src/ontology/ext_bkp.owl
robot convert --input src/ontology/ext_bkp.owl --output src/ontology/ext.owl
```

Load local doid.owl file from repo with Python + owlready2 & produce output:
```python
from owlready2 import *

onto_path.append("src/ontology")
doid = get_ontology("http://purl.obolibrary.org/obo/doid.owl")
doid.load()

obo = doid.get_namespace("http://purl.obolibrary.org/obo/")
print(obo.DOID_4)

for c in doid.classes():
    print(c)
```
</details>

As an alternative, we could request that the authors of owlready2 add an OWL functional syntax parser.
